// Open3DModel → atlas: limpieza de nombres, sistema, zona, id y nombre en español.
// Lo usa extraer-o3d.mjs. Una pieza sin sistema se descarta; una sin nombre en
// español hace fallar la extracción.

// ─── Nombres del OBJ ─────────────────────────────────────────────────────────
// Los objetos traen el lado pegado de mil maneras («Humerus.r», «Scapula.r.»,
// «Talus.r_​», con espacios de ancho cero o tabuladores): todos son derechos.
export function limpiar(crudo) {
  let n = crudo.replace(/[​\t]/g, '').trim()
    .replace(/[._\s]+r[._\s]*$/i, '')
    .replace(/[._\s]+$/, '')
    .replace(/_/g, ' ').replace(/\s+/g, ' ').trim();
  return RENOMBRAR[n] ?? n;
}
const RENOMBRAR = {
  'Annulus fibrosus L1 L20': 'Annulus fibrosus L1 L2', // errata del archivo del miembro superior
};

const EXCLUIR = new Set([
  // Espacios y regiones, no estructuras: volúmenes que taparían lo de dentro.
  'Adductor canal', 'Adductor hiatus', 'Femoral canal', 'Femoral ring', 'Femoral triangle', 'Saphenous opening',
  // Un «todo» que repite sus partes (medido: las partes están 76-100 % encima):
  // se quedan las partes, que son lo que se enseña y la búsqueda las encuentra igual.
  'Trapezius muscle', 'Deltoid muscle', 'Pectoralis major', 'Adductor pollicis',
  'Subacromial-subdeltoid bursa', // = subacromial + subdeltoidea
  'Coracoclavicular ligament', // = conoideo + trapezoide
  'Collateral ligaments of metacarpal joints', // repite los colaterales metacarpofalángicos
  'Medial collateral artery', // la colateral media duplicada (100 % encima)
  'Ligaments of fibular head', // = anterior + posterior
  'Bifurcatum ligament', // = sus dos fascículos (calcaneonavicular y calcaneocuboideo)
]);

// ─── Sistema ─────────────────────────────────────────────────────────────────
const HUESOS = new Set([
  'Occipital bone', 'Mandible', // de Z-Anatomy (za-a-obj.py)
  'Atlas (C1)', 'Axis (C2)', 'Sacrum', 'Coccyx', 'Manubrium of sternum', 'Body of sternum', 'Xiphoid process',
  'Clavicle', 'Scapula', 'Humerus', 'Radius', 'Ulna', 'Scaphoid', 'Lunate bone', 'Triquetrum', 'Pisiform',
  'Trapezium', 'Trapezoid', 'Capitate', 'Hamate', 'Sesamoid bones of hand', 'Sesamoid bones of foot',
  'Hip bone', 'Femur', 'Patella', 'Tibia', 'Fibula', 'Talus', 'Calcaneus', 'Navicular bone', 'Cuboid bone',
  'Medial cuneiform bone', 'Intermediate cuneiform bone', 'Lateral cuneiform bone',
  'First metatarsal bone', 'Second metatarsal bone', 'Third metatarsal bone', 'Fourth metatarsal bone', 'Fifth metatarsal bone',
]);
const SISTEMA_FIJO = {
  'Tensor fasciae latae': 'musculo', // lleva «fascia» en el nombre
  'Communicating br.of Posterior tibial a. and Femoral a': 'arteria',
  'Femoral neck vessels': 'arteria',
  'Dorsalis indicis': 'arteria',
  'Dorsalis pollicis': 'arteria',
  'Radialis indicis': 'arteria',
  'Palmar carpal branches': 'arteria',
  'Dorsal carpal network': 'arteria',
  'Arachnoid mater': 'nervio',
  'Intercarpal articulations': 'conectivo',
};
export function sistemaDe(en) {
  if (EXCLUIR.has(en)) return null;
  if (SISTEMA_FIJO[en]) return SISTEMA_FIJO[en];
  if (HUESOS.has(en) || /^(Cervical|Thoracic|Lumbar) vertebra \(|^Rib \(\d|^Costal cart of|^\d(st|nd|rd|th) metacarpal bone$|phalanx of|^annulus fibrosus|^Nucleus pulposus/i.test(en)) return 'hueso';
  if (/vein|venous/i.test(en)) return 'vena';
  if (/nerve|plexus|root$|lumbosacral trunk|sympathic trunk|spinal cord/i.test(en)) return 'nervio';
  if (/arter|\barch$|arch\b(?! of)|perforating br|cervical trunk$|brachiocephalic/i.test(en)) return 'arteria';
  if (/ligament|\blig\b|capsule|bursa|sheath|vaginae|retinacul|fascia|aponeurosis|membrane|labrum|menisc|disc\b|art cart|articular cartilage|synovial|septum|tract|recess|fat pad|zona orbicularis|syndesmosis|symphysis|fibrous|extensor hood|extensor apparatus|lateral band|intertendinous|tendinous arch/i.test(en)) return 'conectivo';
  return 'musculo';
}

// ─── Zona ────────────────────────────────────────────────────────────────────
// Esqueleto axial y lo que va con él: la misma zona en las dos regiones, para
// que las piezas compartidas (T12-L5, sacro) no cambien de zona según qué
// región se cargó primero.
const AXIAL = /vertebra|^atlas|^axis|^art cart of (atlas|axis|sacrum)|sacrum|coccyx|sacrococcygeal|annulus fibrosus|nucleus pulposus|^rib \(|rib art cart|costal cart|sternum|manubrium|xiphoid|sternocostal|spinal cord|sympathic|arachnoid|intercornual/i;
// Lo que se añade de Z-Anatomy para las inserciones del trapecio (línea nucal
// superior, protuberancia occipital, ligamento nucal) y del platisma (mandíbula).
const CUELLO = new Set(['Platysma', 'Occipital bone', 'Mandible', 'Nuchal ligament']);

export const REGIONES_O3D = {
  'miembro-superior-derecho': {
    nombre: 'Miembro superior derecho',
    lado: 'derecho',
    // Cortes por la altura del centro (Open3DModel): bajo la escápula (1,255 m)
    // y la cabeza humeral → brazo; codo (1,10 m); muñeca (semilunar, 0,85-0,86 m).
    zona(en, [, y]) {
      if (CUELLO.has(en)) return 'cuello';
      if (AXIAL.test(en)) return 'tronco';
      if (y > 1.29) return 'hombro';
      if (y > 1.1) return 'brazo';
      if (y > 0.862) return 'antebrazo';
      return 'mano';
    },
  },
  'miembro-inferior-derecho': {
    nombre: 'Miembro inferior derecho',
    lado: 'derecho',
    // Cortes: bajo la cabeza femoral (0,88 m) y la tuberosidad isquiática;
    // sobre la rótula (0,42-0,47 m: la rodilla va con la pierna, como en el
    // sílabo); maléolos (0,075 m).
    zona(en, [, y]) {
      if (AXIAL.test(en)) return 'tronco';
      if (y > 0.83) return 'pelvis';
      if (y > 0.47) return 'muslo';
      if (y > 0.075) return 'pierna';
      return 'pie';
    },
  },
};

// ─── Id ──────────────────────────────────────────────────────────────────────
// Las piezas que vienen idénticas en los dos archivos (misma caja al micrómetro)
// comparten id, así el visor las pinta una vez al cargar las dos regiones. El
// resto lleva prefijo de región: «Dorsal digital veins» es de la mano en un
// archivo y del pie en el otro.
const COMPARTIDAS = new Set([
  'Thoracic vertebra (T12)', 'Lumbar vertebra (L1)', 'Lumbar vertebra (L2)', 'Lumbar vertebra (L3)',
  'Lumbar vertebra (L4)', 'Lumbar vertebra (L5)', 'Sacrum',
  'Annulus fibrosus T12 L1', 'Annulus fibrosus L1 L2', 'Annulus fibrosus L2 L3', 'Annulus fibrosus L3 L4',
  'Annulus fibrosus L4 L5', 'Annulus fibrosus L5 S1',
]);
const slug = (s) => s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
export function idDe(region, en, fuente = 'o3d') {
  const base = `${fuente}-${slug(en)}`;
  if (COMPARTIDAS.has(en)) return base;
  return `${region === 'miembro-superior-derecho' ? 'ms' : 'mi'}-${base}`;
}

// ─── Nombre en español ───────────────────────────────────────────────────────
const N = { first: 1, second: 2, third: 3, fourth: 4, fifth: 5 };
const ORD_M = ['', 'Primer', 'Segundo', 'Tercer', 'Cuarto', 'Quinto'];
const DEDO_MANO = ['', 'pulgar', 'índice', 'dedo medio', 'anular', 'meñique'];
const DEDO_PIE = ['', 'dedo gordo', 'segundo dedo', 'tercer dedo', 'cuarto dedo', 'quinto dedo'];
const FALANGE = { Proximal: 'proximal', Middle: 'media', Distal: 'distal' };
const dedoMano = (s) => ({ '1st': 1, '2d': 2, '2nd': 2, '3d': 3, '3rd': 3, '4th': 4, '5th': 5 })[s];

const PATRONES = [
  [/^(\d+)(?:st|nd|rd|th) rib art cart of (head|tubercle)$/, (n, p) => `Cartílago articular ${p === 'head' ? 'de la cabeza' : 'del tubérculo'} de la ${n}.ª costilla`],
  [/^Costal cart of (\d+)(?:st|nd|rd|th)\.?rib$/, (n) => `Cartílago costal de la ${n}.ª costilla`],
  [/^Rib \((\d+)(?:st|nd|rd|th)\)$/, (n) => `${n}.ª costilla`],
  [/^(?:Cervical|Thoracic|Lumbar) vertebra \(([CTL]\d+)\)$/, (c) => `Vértebra ${c}`],
  [/^annulus fibrosus ([CTLS]\d+) ([CTLS]\d+)$/i, (a, b) => `Anillo fibroso ${a}-${b}`],
  [/^Nucleus pulposus ([CTL]\d+)-([TLS]\d+)$/, (a, b) => `Núcleos pulposos ${a}-${b}`],
  [/^Vertebra ([CTL]\d+) art cart$/, (c) => `Cartílagos articulares de ${c}`],
  [/^([CTLS]\d) root$/, (c) => `Raíz ${c}`],
  [/^(\d)(?:st|nd|rd|th) [Dd]orsal interosse(?:us|i muscles) of (hand|foot)$/, (n, d) => `${ORD_M[n]} interóseo dorsal ${d === 'hand' ? 'de la mano' : 'del pie'}`],
  [/^(\d)(?:st|nd|rd|th) palmar interosseus of hand$/, (n) => `${ORD_M[n]} interóseo palmar`],
  [/^(\d)(?:st|nd|rd|th) lumbrical of hand$/, (n) => `${ORD_M[n]} lumbrical de la mano`],
  [/^(\d)(?:st|nd|rd|th) metacarpal bone$/, (n) => `${ORD_M[n]} metacarpiano`],
  [/^(First|Second|Third|Fourth|Fifth) metatarsal bone$/, (w) => `${ORD_M[N[w.toLowerCase()]]} metatarsiano`],
  [/^(Proximal|Middle|Distal) phalanx of (1st|2d|3d|3rd|4th|5th) finger$/, (f, d) => `Falange ${FALANGE[f]} del ${DEDO_MANO[dedoMano(d)]}`],
  [/^(Proximal|Middle|Distal) phalanx of (first|second|third|fourth|fifth) finger of foot$/, (f, d) => `Falange ${FALANGE[f]} del ${DEDO_PIE[N[d]]}`],
  [/^Annular ligament\((A\d)\) of 1st finger$/, (a) => `Polea anular ${a} del pulgar`],
  [/^Annular ligaments of (\d)(?:st|nd|rd|th) (finger|toe) A1-A5$/, (n, d) => `Poleas anulares A1-A5 del ${d === 'finger' ? DEDO_MANO[n] : DEDO_PIE[n]}`],
  [/^Cruciform ligaments (?:of|or) (\d)(?:st|nd|rd|th) (finger|toe)$/, (n, d) => `Poleas cruciformes del ${d === 'finger' ? DEDO_MANO[n] : DEDO_PIE[n]}`],
  [/^Extensor hood of (\d)(?:st|nd|rd|th) finger$/, (n) => `Capuchón extensor del ${DEDO_MANO[n]}`],
  [/^Lateral band of (\d)(?:st|nd|rd|th) finger$/, (n) => `Bandeleta lateral del ${DEDO_MANO[n]}`],
  [/^Extensor apparatus of (\d)(?:st|nd|rd|th) toe$/, (n) => `Aparato extensor del ${DEDO_PIE[n]}`],
];

export function nombreDe(region, en) {
  const v = NOMBRES[en];
  if (v) return typeof v === 'string' ? v : v[region === 'miembro-superior-derecho' ? 's' : 'i'];
  for (const [re, f] of PATRONES) {
    const m = en.match(re);
    if (m) return f(...m.slice(1));
  }
  return null;
}

// Terminología Anatómica en español; entre paréntesis el nombre clásico que
// aún se usa en clase cuando difiere. Sin lado: todo es derecho.
// Un valor { s, i } distingue el mismo nombre inglés en el miembro superior (s)
// y en el inferior (i).
const NOMBRES = {
  // ── De Z-Anatomy ──
  'Platysma': 'Platisma',
  'Occipital bone': 'Hueso occipital',
  'Mandible': 'Mandíbula',
  'Nuchal ligament': 'Ligamento nucal',
  // ── Huesos ──
  'Atlas (C1)': 'Atlas (C1)',
  'Axis (C2)': 'Axis (C2)',
  'Sacrum': 'Sacro',
  'Coccyx': 'Cóccix',
  'Manubrium of sternum': 'Manubrio del esternón',
  'Body of sternum': 'Cuerpo del esternón',
  'Xiphoid process': 'Apófisis xifoides',
  'Clavicle': 'Clavícula',
  'Scapula': 'Escápula',
  'Humerus': 'Húmero',
  'Radius': 'Radio',
  'Ulna': 'Cúbito (ulna)',
  'Scaphoid': 'Escafoides',
  'Lunate bone': 'Semilunar',
  'Triquetrum': 'Piramidal',
  'Pisiform': 'Pisiforme',
  'Trapezium': 'Trapecio (hueso)',
  'Trapezoid': 'Trapezoide',
  'Capitate': 'Grande (hueso)',
  'Hamate': 'Ganchoso',
  'Sesamoid bones of hand': 'Sesamoideos de la mano',
  'Sesamoid bones of foot': 'Sesamoideos del pie',
  'Hip bone': 'Coxal',
  'Femur': 'Fémur',
  'Patella': 'Rótula',
  'Tibia': 'Tibia',
  'Fibula': 'Fíbula (peroné)',
  'Talus': 'Talus (astrágalo)',
  'Calcaneus': 'Calcáneo',
  'Navicular bone': 'Navicular',
  'Cuboid bone': 'Cuboides',
  'Medial cuneiform bone': 'Cuneiforme medial',
  'Intermediate cuneiform bone': 'Cuneiforme intermedio',
  'Lateral cuneiform bone': 'Cuneiforme lateral',

  // ── Cartílagos articulares ──
  'art cart of Atlas C1': 'Cartílago articular del atlas',
  'art cart of Axis C2': 'Cartílago articular del axis',
  'Art cart of calcaneus': 'Cartílago articular del calcáneo',
  'Art cart of capitate bone': 'Cartílago articular del grande',
  'Art cart of cuboid bone': 'Cartílago articular del cuboides',
  'Art cart of femur distal end': 'Cartílago articular del extremo distal del fémur',
  'Art cart of femur head': 'Cartílago articular de la cabeza del fémur',
  'Art cart of fibula proximal tibiofibular joint': 'Cartílago articular tibiofibular proximal (fíbula)',
  'Art cart of fibula talofibular joint': 'Cartílago articular talofibular (fíbula)',
  'Art cart of hamate bone': 'Cartílago articular del ganchoso',
  'Art cart of hip bone pubis': 'Cartílago articular de la sínfisis (pubis)',
  'Art cart of humerus distal end': 'Cartílago articular del extremo distal del húmero',
  'Art cart of humerus head': 'Cartílago articular de la cabeza del húmero',
  'Art cart of intermediate cuneiform bone': 'Cartílago articular del cuneiforme intermedio',
  'Art cart of lateral cuneiform bone': 'Cartílago articular del cuneiforme lateral',
  'Art cart of lunate bone': 'Cartílago articular del semilunar',
  'Art cart of medial cuneiform bone': 'Cartílago articular del cuneiforme medial',
  'Art cart of navicular bone': 'Cartílago articular del navicular',
  'Art cart of patella': 'Cartílago articular de la rótula',
  'Art cart of pisiform bone': 'Cartílago articular del pisiforme',
  'Art cart of radius distal end': 'Cartílago articular del extremo distal del radio',
  'Art cart of radius head': 'Cartílago articular de la cabeza del radio',
  'Art cart of sacrococcygeal joint on coccyx': 'Cartílago articular sacrococcígeo (cóccix)',
  'Art cart of sacrococcygeal joint on sacrum': 'Cartílago articular sacrococcígeo (sacro)',
  'Art cart of sacroiliac joint on hip bone': 'Cartílago articular sacroilíaco (coxal)',
  'Art cart of sacroiliac joint on sacrum': 'Cartílago articular sacroilíaco (sacro)',
  'art cart of sacrum art process': 'Cartílago articular de las apófisis articulares del sacro',
  'art cart of sacrum lumbosacral joint': 'Cartílago articular lumbosacro (sacro)',
  'Art cart of scaphoid bone': 'Cartílago articular del escafoides',
  'Art cart of Sesamoid bones': 'Cartílago articular de los sesamoideos del pie',
  'art cart of sternoclavicular joint on manubrium': 'Cartílago articular esternoclavicular (manubrio)',
  'art cart of sternocostal joint on manubrium': 'Cartílago articular esternocostal (manubrio)',
  'art cart of sternocostal joints on sternal body': 'Cartílagos articulares esternocostales (cuerpo del esternón)',
  'Art cart of talus': 'Cartílago articular del talus',
  'Art cart of tibia distal end': 'Cartílago articular del extremo distal de la tibia',
  'Art cart of tibia proximal end': 'Cartílago articular del extremo proximal de la tibia',
  'Art cart of tibia proximal tibiofibular joint': 'Cartílago articular tibiofibular proximal (tibia)',
  'Art cart of trapezium bone': 'Cartílago articular del trapecio',
  'Art cart of trapezoid bone': 'Cartílago articular del trapezoide',
  'Art cart of triquetrum bone': 'Cartílago articular del piramidal',
  'Art cart of ulna (proximal end)': 'Cartílago articular del extremo proximal del cúbito',
  'Art cart of ulna. (distal end)': 'Cartílago articular del extremo distal del cúbito',
  'Art carts of distal phalanges': 'Cartílagos articulares de las falanges distales de la mano',
  'Art carts of distal phalanges of foot': 'Cartílagos articulares de las falanges distales del pie',
  'Art carts of metacarpal bones': 'Cartílagos articulares de los metacarpianos',
  'Art carts of metatarsal bones': 'Cartílagos articulares de los metatarsianos',
  'Art carts of middle phalanges': 'Cartílagos articulares de las falanges medias de la mano',
  'Art carts of middle phalanges of foot': 'Cartílagos articulares de las falanges medias del pie',
  'Art carts of proximal phalanges': 'Cartílagos articulares de las falanges proximales de la mano',
  'Art carts of proximal phalanges of foot': 'Cartílagos articulares de las falanges proximales del pie',
  'Articular cartilage of acromioclavicular joint on clavicle': 'Cartílago articular acromioclavicular (clavícula)',
  'Articular cartilage of acromioclavicular joint on scapula': 'Cartílago articular acromioclavicular (escápula)',
  'Articular cartilage of glenohumeral joint on scapula': 'Cartílago articular de la cavidad glenoidea',
  'Articular cartilage of hip bone acetabulum': 'Cartílago articular del acetábulo',
  'Articular cartilage of sternoclavicular joint on clavicle': 'Cartílago articular esternoclavicular (clavícula)',

  // ── Articulaciones: cápsulas, discos, labrum ──
  'Acetabular labrum': 'Labrum acetabular (rodete cotiloideo)',
  'Glenoid labrum': 'Labrum glenoideo (rodete glenoideo)',
  'Acromioclavicular capsule': 'Cápsula acromioclavicular',
  'Acromioclavicular disc': 'Disco acromioclavicular',
  'Articular disc of steroclavicular joint': 'Disco articular esternoclavicular',
  'Sternoclavicular capsule': 'Cápsula esternoclavicular',
  'Articular capsule of elbow joint': 'Cápsula articular del codo',
  'Articular capsule of glenohumeral joint': 'Cápsula articular glenohumeral',
  'Articular capsule of knee joint': 'Cápsula articular de la rodilla',
  'Articular capsule of radiocarpal joint': 'Cápsula articular radiocarpiana',
  'Articular capsules of distal interphalangeal joints': {
    s: 'Cápsulas articulares interfalángicas distales de la mano',
    i: 'Cápsulas articulares interfalángicas distales del pie',
  },
  'Articular capsules of metacarpophalangeal joints': 'Cápsulas articulares metacarpofalángicas',
  'Articular capsules of metatarsophalangeal joints': 'Cápsulas articulares metatarsofalángicas',
  'Articular capsules of proximal interphalangeal': 'Cápsulas articulares interfalángicas proximales del pie',
  'Articular capsules of proximal interphalangeal joints': 'Cápsulas articulares interfalángicas proximales de la mano',
  'Capsule of talocrural joint': 'Cápsula articular talocrural (tobillo)',
  'Hip joint capsule': 'Cápsula articular de la cadera',
  'Zona orbicularis of hip joint': 'Zona orbicular de la cadera',
  'Intercarpal articulations': 'Articulaciones intercarpianas',
  'Interpubic disc': 'Disco interpúbico',
  'Symphysis of sacrococcygeal joint': 'Sínfisis sacrococcígea',
  'Triangular fibro cartilage disc': 'Disco articular radiocubital (fibrocartílago triangular)',
  'Synovial membranes of knee': 'Membrana sinovial de la rodilla',
  'Subpopliteal recess': 'Receso subpoplíteo',
  'Infrapatellar fat pad': 'Cuerpo adiposo infrarrotuliano (de Hoffa)',
  'Lateral meniscus': 'Menisco lateral',
  'Medial meniscus': 'Menisco medial',
  'Anterior horn of Lateral meniscus': 'Asta anterior del menisco lateral',
  'Anterior horn of Medial meniscus': 'Asta anterior del menisco medial',
  'Posterior horn of Lateral meniscus': 'Asta posterior del menisco lateral',
  'Posterior horn of Medial meniscus': 'Asta posterior del menisco medial',
  'Oblique cord or radio-ulnar syndesmosis': 'Cuerda oblicua (sindesmosis radiocubital)',

  // ── Ligamentos ──
  'Acromioclavicular ligament': 'Ligamento acromioclavicular',
  'Anterior cruciate ligament': 'Ligamento cruzado anterior',
  'Posterior cruciate ligament': 'Ligamento cruzado posterior',
  'Anterior ligament of fibular head': 'Ligamento anterior de la cabeza de la fíbula',
  'Posterior ligament of fibular head': 'Ligamento posterior de la cabeza de la fíbula',
  'Anterior pubic ligament': 'Ligamento púbico anterior',
  'Posterior pubic ligament': 'Ligamento púbico posterior',
  'Sup, Inf, Ant, Post, Pubic ligaments': 'Ligamentos del pubis (superior, inferior, anterior y posterior)',
  'Anterior sacro-iliac ligament': 'Ligamento sacroilíaco anterior',
  'Interossea / Posterior sacro-iliac ligament': 'Ligamentos sacroilíacos interóseo y posterior',
  'Anterior sternoclavicular ligament': 'Ligamento esternoclavicular anterior',
  'Posterior Sternoclavicular ligament': 'Ligamento esternoclavicular posterior',
  'Interclavicular ligament': 'Ligamento interclavicular',
  'Costoclavicular ligament': 'Ligamento costoclavicular',
  'Anterior talocalcaneal ligament': 'Ligamento talocalcáneo anterior',
  'Posterior talocalcaneal ligament': 'Ligamento talocalcáneo posterior',
  'Medial talocalcaneal ligament': 'Ligamento talocalcáneo medial',
  'Interosseus talocalcaneal ligament': 'Ligamento talocalcáneo interóseo',
  'Cervical ligament (anterior talocalcaneal ligament)': 'Ligamento cervical del tarso',
  'Anterior talofibular ligament': 'Ligamento talofibular anterior',
  'Posterior talofibular ligament': 'Ligamento talofibular posterior',
  'Calcaneofibular ligament': 'Ligamento calcaneofibular',
  'Anterior tibiofibular ligament': 'Ligamento tibiofibular anterior',
  'Posterior tibiofibular ligament': 'Ligamento tibiofibular posterior',
  'Transverse tibiofibular ligament': 'Ligamento tibiofibular transverso',
  'Anterior tibiotalar ligament (Tibiospring lig.)': 'Ligamento tibiotalar anterior (deltoideo)',
  'Posterior tibiotalar ligament': 'Ligamento tibiotalar posterior (deltoideo)',
  'Tibiocalcaneal ligament': 'Ligamento tibiocalcáneo (deltoideo)',
  'Tibionavicular ligament': 'Ligamento tibionavicular (deltoideo)',
  'Arcuate ligament': 'Ligamento poplíteo arqueado',
  'Oblique popliteal ligament': 'Ligamento poplíteo oblicuo',
  'Calcaneocuboid ligament': 'Ligamento bifurcado (fascículo calcaneocuboideo)',
  'Calcaneonavicular ligament': 'Ligamento bifurcado (fascículo calcaneonavicular)',
  'Dorsal calcaneocuboid ligament': 'Ligamento calcaneocuboideo dorsal',
  'Plantar calcaneocuboid ligament': 'Ligamento calcaneocuboideo plantar',
  'Plantar calcaneonavicular ligament': 'Ligamento calcaneonavicular plantar (en resorte)',
  'Dorsal cuboidonavicular ligament': 'Ligamento cuboideonavicular dorsal',
  'Plantar cuboideonavicular ligament': 'Ligamento cuboideonavicular plantar',
  'Dorsal cuneocuboid ligament': 'Ligamento cuneocuboideo dorsal',
  'Plantar cuneocuboid ligament': 'Ligamento cuneocuboideo plantar',
  'Dorsal cuneonavicular ligaments': 'Ligamentos cuneonaviculares dorsales',
  'Plantar cuneonavicular ligaments': 'Ligamentos cuneonaviculares plantares',
  'Dorsal intercuneiform ligaments': 'Ligamentos intercuneiformes dorsales',
  'Plantar intercuneiform ligaments': 'Ligamentos intercuneiformes plantares',
  'Intercuneiform interosseus ligaments': 'Ligamentos intercuneiformes interóseos',
  'Cuneometatarsal interosseus ligaments': 'Ligamentos cuneometatarsianos interóseos',
  'Dorsal tarsometatarsal ligaments': 'Ligamentos tarsometatarsianos dorsales',
  'Plantar tarsometatarsal ligaments': 'Ligamentos tarsometatarsianos plantares',
  'Dorsal metatarsal ligaments': 'Ligamentos metatarsianos dorsales',
  'Plantar metatarsal ligaments': 'Ligamentos metatarsianos plantares',
  'Metatarsal interosseous ligaments': 'Ligamentos metatarsianos interóseos',
  'Deep transverse metatarsal ligament': 'Ligamento metatarsiano transverso profundo',
  'Superficial transverse metatarsal ligament': 'Ligamento metatarsiano transverso superficial',
  'Talonavicular ligament': 'Ligamento talonavicular',
  'Long plantar ligament': 'Ligamento plantar largo',
  'Intersesamoid ligament': 'Ligamento intersesamoideo',
  'Collateral ligaments of metatarsophalangeal joints': 'Ligamentos colaterales metatarsofalángicos',
  'Collateral ligament of proximal interphalangeal joints': 'Ligamentos colaterales interfalángicos proximales del pie',
  'Collateral ligaments of distal interphalangeal joints': 'Ligamentos colaterales interfalángicos distales del pie',
  'Palmar ligaments of metatarsophalangeal joints': 'Ligamentos plantares metatarsofalángicos',
  'Palmar ligament of proximal interphalangeal joints': 'Ligamentos plantares interfalángicos proximales del pie',
  'Palmar ligaments of distal interphalangeal joints': 'Ligamentos plantares interfalángicos distales del pie',
  'Medial collatertal ligament': 'Ligamento colateral tibial (medial de la rodilla)',
  'Fibular collateral ligament': 'Ligamento colateral fibular (lateral de la rodilla)',
  'Posterior meniscofemoral ligament': 'Ligamento meniscofemoral posterior',
  'Transverse ligament of knee': 'Ligamento transverso de la rodilla',
  'Quadriceps common tendon and patellar ligament': 'Tendón del cuádriceps y ligamento rotuliano',
  'Descending part of Iliofemoral ligament': 'Ligamento iliofemoral (porción descendente)',
  'Transverse part of Iliofemoral ligament': 'Ligamento iliofemoral (porción transversa)',
  'Ishciofemoral ligament': 'Ligamento isquiofemoral',
  'Pubofemoral ligament': 'Ligamento pubofemoral',
  'Ligament of head of femur': 'Ligamento de la cabeza del fémur (redondo)',
  'Transverse acetabular ligament': 'Ligamento transverso del acetábulo',
  'Iliolumbar ligament': 'Ligamento iliolumbar',
  'Sacrospinous ligament': 'Ligamento sacroespinoso',
  'Sacrotuberal ligament': 'Ligamento sacrotuberoso',
  'Intercornual ligament': 'Ligamento intercornual (sacrococcígeo)',
  'Obturator membrane': 'Membrana obturatriz',
  'Coraco-acromial ligament': 'Ligamento coracoacromial',
  'Conoid ligament (part of coracoclavicular ligament)': 'Ligamento conoideo',
  'Trapezoid ligament (part of coracoclavicular ligament)': 'Ligamento trapezoide',
  'Coracohumeral ligament': 'Ligamento coracohumeral',
  'Superior glenohumeral ligament': 'Ligamento glenohumeral superior',
  'Middle glenohumeral ligament': 'Ligamento glenohumeral medio',
  'Inferior glenohumeral ligament': 'Ligamento glenohumeral inferior',
  'Transverse humeral ligament': 'Ligamento humeral transverso',
  'Superior transverse scapular ligament': 'Ligamento transverso superior de la escápula',
  'Inferior transverse scapular ligament': 'Ligamento transverso inferior de la escápula',
  'Radial annular ligament': 'Ligamento anular del radio',
  'Quadrate ligament': 'Ligamento cuadrado',
  'Radial collateral ligament of elbow': 'Ligamento colateral radial del codo',
  'Ulnar collateral ligament of elbow': 'Ligamento colateral cubital del codo',
  'Radial collateral ligament of wrist': 'Ligamento colateral radial del carpo',
  'Ulnar collateral ligament of wrist': 'Ligamento colateral cubital del carpo',
  'Dorsal radio-ulnar ligament': 'Ligamento radiocubital dorsal',
  'Palmar radio-ulnar ligament': 'Ligamento radiocubital palmar',
  'Dorsal radiocarpal ligament': 'Ligamento radiocarpiano dorsal',
  'Palmar radiocarpal ligament': 'Ligamento radiocarpiano palmar',
  'Dorsal ulnocarpal ligament': 'Ligamento cubitocarpiano dorsal',
  'Palmar ulnocarpal ligament': 'Ligamento cubitocarpiano palmar',
  'Ulnopisiform ligament': 'Ligamento cubitopisiforme',
  'Ulnotriquetral ligament': 'Ligamento cubitopiramidal',
  'Radiate carpal ligament': 'Ligamento radiado del carpo',
  'Radioscaphocapitate ligament': 'Ligamento radioescafogrande',
  'Dorsal intercarpal ligament': 'Ligamento intercarpiano dorsal',
  'Dorsal scaphotriquetral ligament': 'Ligamento escafopiramidal dorsal',
  'Palmar scaphotriquetral ligament': 'Ligamento escafopiramidal palmar',
  'Scaphocapitate ligament': 'Ligamento escafogrande',
  'Scapholunate interosseus ligament': 'Ligamento interóseo escafosemilunar',
  'Scaphotrapeziotrapezoidal ligament': 'Ligamento escafotrapeciotrapezoideo',
  'Lunotriquetral interosseous ligament': 'Ligamento interóseo semilunar-piramidal',
  'Palmar lunotriquetral ligament': 'Ligamento semilunar-piramidal palmar',
  'Triquetrocapitate ligament': 'Ligamento piramidal-grande',
  'Triquetrohamate ligament': 'Ligamento piramidal-ganchoso',
  'Capitohamate interosseus ligament': 'Ligamento interóseo grande-ganchoso',
  'Palmar capitohamate ligament': 'Ligamento grande-ganchoso palmar',
  'Trapeziotrapezoidal interosseous ligament': 'Ligamento interóseo trapecio-trapezoide',
  'Trapezoideocapitate interosseous ligament': 'Ligamento interóseo trapezoide-grande',
  'Palmar trapezoideocapitate ligament': 'Ligamento trapezoide-grande palmar',
  'Pisohamate ligament': 'Ligamento pisoganchoso',
  'Pisometacarpal ligament': 'Ligamento pisometacarpiano',
  'Pisotriquetral ligament': 'Ligamento pisopiramidal',
  'Dorsal carpometacarpal ligaments': 'Ligamentos carpometacarpianos dorsales',
  'Palmar carpometacarpal ligaments': 'Ligamentos carpometacarpianos palmares',
  'Dorsal metacarpal ligaments': 'Ligamentos metacarpianos dorsales',
  'Palmar metacarpal ligaments': 'Ligamentos metacarpianos palmares',
  'Interosseous metacarpal ligaments': 'Ligamentos metacarpianos interóseos',
  'Deep transverse metacarpal ligament': 'Ligamento metacarpiano transverso profundo',
  'Superficial transverse metacarpal lig': 'Ligamento metacarpiano transverso superficial',
  'Collateral ligaments of metacarpophalangeal joints': 'Ligamentos colaterales metacarpofalángicos',
  'Collateral ligaments of interphalangeal joints': 'Ligamentos colaterales interfalángicos proximales de la mano',
  'Collateral ligaments of distal phalangeal joints': 'Ligamentos colaterales interfalángicos distales de la mano',
  'Palmar ligaments of metacarpophalangeal joints': 'Ligamentos palmares metacarpofalángicos',
  'Palmar ligaments of interphalangeal joints': 'Ligamentos palmares interfalángicos proximales de la mano',
  'Palmar ligaments of distal phalangeal joints': 'Ligamentos palmares interfalángicos distales de la mano',
  'Oblique ligament of 1st finger': 'Polea oblicua del pulgar',

  // ── Fascias, retináculos, tabiques, aponeurosis ──
  'Antebrachial fascia': 'Fascia antebraquial',
  'Thickened part of antebrachial fascia': 'Ligamento carpiano palmar (fascia antebraquial)',
  'Brachial fascia': 'Fascia braquial',
  'Crural fascia': 'Fascia crural',
  'Fascia lata': 'Fascia lata',
  'Iliotibial tract': 'Tracto iliotibial (cintilla de Maissiat)',
  'Aponeurosis palmaris': 'Aponeurosis palmar',
  'Plantar aponeurosis': 'Aponeurosis plantar',
  'Gluteal aponeurosis': 'Aponeurosis glútea',
  'Bicipital aponeurosis': 'Aponeurosis bicipital (lacertus fibrosus)',
  'Extensor retinaculum of wrist': 'Retináculo de los extensores (muñeca)',
  'Flexor retinaculum': 'Retináculo de los flexores (muñeca)',
  'Flexor retinaculum of ankle': 'Retináculo de los flexores (tobillo)',
  'Superior extensor retinaculum of ankle': 'Retináculo superior de los extensores (tobillo)',
  'Inferior extensor retinaculum': 'Retináculo inferior de los extensores (tobillo)',
  'Superior fibular retinaculum': 'Retináculo superior de los fibulares',
  'Inferior fibular retinaculum': 'Retináculo inferior de los fibulares',
  'Lateral patellar retinaculum (horizontal part)': 'Retináculo rotuliano lateral (porción horizontal)',
  'Lateral patellar retinaculum (vertical part)': 'Retináculo rotuliano lateral (porción vertical)',
  'Medial patellar retinaculum (horizontal part)': 'Retináculo rotuliano medial (porción horizontal)',
  'Medial patellar retinaculum (vertical part)': 'Retináculo rotuliano medial (porción vertical)',
  'Interosseous membrane of forearm': 'Membrana interósea del antebrazo',
  'Interosseous membrane of leg': 'Membrana interósea de la pierna',
  'Lateral intermuscular septum of arm': 'Tabique intermuscular lateral del brazo',
  'Medial intermuscular septum of arm': 'Tabique intermuscular medial del brazo',
  'Lateral femoral intermuscular septum': 'Tabique intermuscular femoral lateral',
  'Medial femoral intermuscular septum': 'Tabique intermuscular femoral medial',
  'Anterior intermuscular septum of leg': 'Tabique intermuscular anterior de la pierna',
  'Posterior intermuscular septum of leg': 'Tabique intermuscular posterior de la pierna',
  'Transverse intermuscular septum of leg': 'Tabique intermuscular transverso de la pierna',
  'Tendinous arch of soleus': 'Arco tendinoso del sóleo',
  'Intertendinous connections of extensor digitorum': 'Conexiones intertendinosas del extensor de los dedos',

  // ── Vainas tendinosas y fibrosas ──
  'Abductor pollicis longus tendon sheath': 'Vaina tendinosa del abductor largo del pulgar',
  'Common flexor tendon sheath': 'Vaina común de los tendones flexores',
  'Common tendon sheath of fibularis muscles': 'Vaina tendinosa común de los fibulares',
  'Extensor carpi radialis brevis tendon sheath': 'Vaina tendinosa del extensor radial corto del carpo',
  'Extensor carpi radialis longus tendon sheath': 'Vaina tendinosa del extensor radial largo del carpo',
  'Extensor carpi ulnaris tendon sheath': 'Vaina tendinosa del extensor cubital del carpo',
  'Extensor digiti minimi tendon sheath': 'Vaina tendinosa del extensor del meñique',
  'Extensor digitorum - Extensor indicis tendon sheath': 'Vaina tendinosa de los extensores de los dedos y del índice',
  'Extensor digitorum longus-fibularis tertius vaginae tendinum': 'Vaina tendinosa del extensor largo de los dedos y del fibular tercero',
  'Extensor hallucis longus tendon sheath': 'Vaina tendinosa del extensor largo del dedo gordo',
  'Extensor pollicis brevis tendon sheath': 'Vaina tendinosa del extensor corto del pulgar',
  'Extensor pollicis longus tendon sheath': 'Vaina tendinosa del extensor largo del pulgar',
  'Flexor carpi radialis tendon sheath': 'Vaina tendinosa del flexor radial del carpo',
  'Flexor digitorum longus tendon sheath': 'Vaina tendinosa del flexor largo de los dedos',
  'Flexor hallucis longus tendon sheath': 'Vaina tendinosa del flexor largo del dedo gordo',
  'Flexor pollicis longus tendon sheath': 'Vaina tendinosa del flexor largo del pulgar',
  'Long head of biceps brachii tendon sheath': 'Vaina tendinosa de la cabeza larga del bíceps',
  'Plantar tendinous sheath of fibularis longus': 'Vaina tendinosa plantar del fibular largo',
  'Tibialis anterior tendon sheath': 'Vaina tendinosa del tibial anterior',
  'Tibialis posterior tendon sheath': 'Vaina tendinosa del tibial posterior',
  'Fibrous sheath of digits of hand': 'Vainas fibrosas de los dedos de la mano',
  'Fibrous sheath of digits of hand thumb': 'Vaina fibrosa del pulgar',
  'Fibrous sheath of toes': 'Vainas fibrosas de los dedos del pie',
  'Synovial sheaths of fingers': 'Vainas sinoviales de los dedos de la mano',
  'Synovial sheaths of toes': 'Vainas sinoviales de los dedos del pie',

  // ── Bolsas ──
  'Bicipitoradial bursa': 'Bolsa bicipitorradial',
  'Bursa of piriformis': 'Bolsa del piriforme',
  'Coracobrachial bursa': 'Bolsa coracobraquial',
  'Deep Infrapatellar bursa': 'Bolsa infrarrotuliana profunda',
  'Subcutaneous Infrapatellar bursa': 'Bolsa infrarrotuliana subcutánea',
  'Iliopectineal bursa': 'Bolsa iliopectínea',
  'Inferior subtendinous bursa of biceps femoris': 'Bolsa subtendinosa inferior del bíceps femoral',
  'Superior bursa of biceps femoris': 'Bolsa superior del bíceps femoral',
  'Infraserratus bursa': 'Bolsa infraserrata',
  'Supraserratus bursa': 'Bolsa supraserrata',
  'Intermuscular gluteal bursae': 'Bolsas intermusculares glúteas',
  'Interosseous cubital bursa': 'Bolsa cubital interósea',
  'Intratendinous olecranon bursa': 'Bolsa intratendinosa del olécranon',
  'Subcutaneous olecranon bursa': 'Bolsa subcutánea del olécranon',
  'Lateral subtendinous bursa of gastrocnemius muscle': 'Bolsa subtendinosa lateral del gastrocnemio',
  'Medial subtendinous bursa of gastrocnemius muscle': 'Bolsa subtendinosa medial del gastrocnemio',
  'Pes anserine bursa': 'Bolsa de la pata de ganso',
  'Sciatic bursa of gluteus maximus (Ischiogluteal bursa)': 'Bolsa isquiática del glúteo mayor',
  'Sciatic bursa of obturator internus': 'Bolsa isquiática del obturador interno',
  'Semimembranosus bursa deep to tendon': 'Bolsa del semimembranoso',
  'Subacromial bursa': 'Bolsa subacromial',
  'Subdeltoid bursa': 'Bolsa subdeltoidea',
  'Subcutaneous acromial bursa': 'Bolsa subcutánea acromial',
  'Subcutaneous bursa of lateral malleolus': 'Bolsa subcutánea del maléolo lateral',
  'Subcutaneous bursa of medial malleolus': 'Bolsa subcutánea del maléolo medial',
  'Subcutaneous bursa of tuberosity of tibia': 'Bolsa subcutánea de la tuberosidad tibial',
  'Subcutaneous calcaneal bursa': 'Bolsa subcutánea calcánea',
  'Subcutaneous prepatellar bursa': 'Bolsa prerrotuliana subcutánea',
  'Subfascial prepatellar bursa': 'Bolsa prerrotuliana subfascial',
  'Subtendinous prepatellar bursa': 'Bolsa prerrotuliana subtendinosa',
  'Subcutaneous trochanteric bursa': 'Bolsa trocantérica subcutánea',
  'Suprapatellar bursa overlay': 'Bolsa suprarrotuliana',
  'Subtendinous bursa of iliacus': 'Bolsa subtendinosa del ilíaco',
  'Subtendinous bursa of infraspinatus muscle': 'Bolsa subtendinosa del infraespinoso',
  'Subtendinous bursa of latissimus dorsi': 'Bolsa subtendinosa del dorsal ancho',
  'Subtendinous bursa of obturator internus': 'Bolsa subtendinosa del obturador interno',
  'Subtendinous bursa of sartorius': 'Bolsa subtendinosa del sartorio',
  'Subtendinous bursa of subscapularis': 'Bolsa subtendinosa del subescapular',
  'Subtendinous bursa of teres major': 'Bolsa subtendinosa del redondo mayor',
  'Subtendinous bursa of tibialis anterior': 'Bolsa subtendinosa del tibial anterior',
  'Subtendinous bursa of trapezius': 'Bolsa subtendinosa del trapecio',
  'Subtendinous bursa of triceps brachii': 'Bolsa subtendinosa del tríceps braquial',
  'Subtendinous calcaneal bursa': 'Bolsa subtendinosa calcánea (retrocalcánea)',
  'Trochanteric bursa of gluteus maximus': 'Bolsa trocantérica del glúteo mayor',
  'Trochanteric bursa of gluteus minimus': 'Bolsa trocantérica del glúteo menor',
  'Trochanteric bursae of gluteus medius': 'Bolsas trocantéricas del glúteo medio',

  // ── Músculos del miembro superior ──
  'Descending part of Trapezius muscle': 'Trapecio (porción descendente)',
  'Transverse part of trapezius muscle': 'Trapecio (porción transversa)',
  'Ascending part of Trapezius muscle': 'Trapecio (porción ascendente)',
  'Latissimus dorsi': 'Dorsal ancho',
  'Levator scapulae': 'Elevador de la escápula (angular)',
  'Rhomboid major muscle': 'Romboides mayor',
  'Rhomboid minor muscle': 'Romboides menor',
  'Clavicular head of pectoralis major muscle': 'Pectoral mayor (porción clavicular)',
  'Sternocostal head of pectoralis major muscle': 'Pectoral mayor (porción esternocostal)',
  'Abdominal head of pectoralis major muscle': 'Pectoral mayor (porción abdominal)',
  'Pectoralis minor muscle': 'Pectoral menor',
  'Subclavius muscle': 'Subclavio',
  'Serratus anterior muscle': 'Serrato anterior',
  'Clavicular part of deltoid muscle': 'Deltoides (porción clavicular)',
  'Acromial part of deltoid muscle': 'Deltoides (porción acromial)',
  'Spinal part of deltoid muscle': 'Deltoides (porción espinal)',
  'Supraspinatus muscle': 'Supraespinoso',
  'Infraspinatus muscle': 'Infraespinoso',
  'Teres minor muscle': 'Redondo menor',
  'Teres major muscle': 'Redondo mayor',
  'Subscapularis muscle': 'Subescapular',
  'Long head of biceps brachii': 'Bíceps braquial (cabeza larga)',
  'Short head of biceps brachii': 'Bíceps braquial (cabeza corta)',
  'Common tendon of biceps brachii': 'Tendón del bíceps braquial',
  'Coracobrachialis muscle': 'Coracobraquial',
  'Brachialis muscle': 'Braquial',
  'Long head of triceps brachii': 'Tríceps braquial (cabeza larga)',
  'Lateral head of triceps brachii': 'Tríceps braquial (cabeza lateral)',
  'Medial head of triceps brachii': 'Tríceps braquial (cabeza medial)',
  'Common tendon of triceps brachii': 'Tendón del tríceps braquial',
  'Anconeus muscle': 'Ancóneo',
  'Humeral head of pronator teres': 'Pronador redondo (cabeza humeral)',
  'Ulnar head of pronator teres': 'Pronador redondo (cabeza cubital)',
  'Flexor carpi radialis': 'Flexor radial del carpo (palmar mayor)',
  'Palmaris longus muscle': 'Palmar largo (palmar menor)',
  'Palmaris brevis muscle': 'Palmar corto',
  'Humeral head of flexor carpi ulnaris': 'Flexor cubital del carpo (cabeza humeral)',
  'Ulnar head of flexor carpi ulnaris': 'Flexor cubital del carpo (cabeza cubital)',
  'Common tendon of flexor carpi ulnaris': 'Tendón del flexor cubital del carpo',
  'Flexor digitorum superficialis humero-ulnar head': 'Flexor superficial de los dedos (cabeza humerocubital)',
  'Flexor digitorum superficialis radial head': 'Flexor superficial de los dedos (cabeza radial)',
  'Flexor digitorum profundus': 'Flexor profundo de los dedos',
  'Flexor pollicis longus': 'Flexor largo del pulgar',
  'Pronator quadratus': 'Pronador cuadrado',
  'Brachioradialis muscle': 'Braquiorradial (supinador largo)',
  'Extensor carpi radialis longus': 'Extensor radial largo del carpo (1.er radial)',
  'Extensor carpi radialis brevis': 'Extensor radial corto del carpo (2.º radial)',
  'Extensor digitorum': 'Extensor de los dedos',
  'Extensor digiti minimi': 'Extensor del meñique',
  'Humeral head of extensor carpi ulnaris': 'Extensor cubital del carpo (cabeza humeral)',
  'Ulnar head of extensor carpi ulnaris': 'Extensor cubital del carpo (cabeza cubital)',
  'Common tendon of extensor carpi ulnaris': 'Tendón del extensor cubital del carpo',
  'Supinator': 'Supinador',
  'Abductor pollicis longus': 'Abductor largo del pulgar',
  'Extensor pollicis brevis': 'Extensor corto del pulgar',
  'Extensor pollicis longus': 'Extensor largo del pulgar',
  'Extensor indicis': 'Extensor del índice',
  'Abductor pollicis brevis': 'Abductor corto del pulgar',
  'Superficial head of flexor pollicis brevis': 'Flexor corto del pulgar (cabeza superficial)',
  'Deep head of flexor pollicis brevis': 'Flexor corto del pulgar (cabeza profunda)',
  'Opponens pollicis muscle': 'Oponente del pulgar',
  'Oblique head of adductor pollicis': 'Aductor del pulgar (cabeza oblicua)',
  'Transverse head of adductor pollicis': 'Aductor del pulgar (cabeza transversa)',
  'Abductor digiti minimi': 'Abductor del meñique',
  'Flexor digiti minimi brevis of hand': 'Flexor corto del meñique',
  'Opponens digiti minimi muscle of hand': 'Oponente del meñique',

  // ── Músculos del miembro inferior ──
  'Psoas major': 'Psoas mayor',
  'Psoas minor': 'Psoas menor',
  'Iliacus muscle': 'Ilíaco',
  'Gluteus maximus muscle': 'Glúteo mayor',
  'Gluteus medius muscle': 'Glúteo medio',
  'Gluteus minimus muscle': 'Glúteo menor',
  'Tensor fasciae latae': 'Tensor de la fascia lata',
  'Piriformis muscle': 'Piriforme',
  'Superior gemellus muscle': 'Gemelo superior',
  'Inferior gemellus muscle': 'Gemelo inferior',
  'Obturator internus': 'Obturador interno',
  'Obturator externus': 'Obturador externo',
  'Quadratus femoris muscle': 'Cuadrado femoral',
  'Coccygeus muscle': 'Coccígeo',
  'Sartorius muscle': 'Sartorio',
  'Rectus femoris': 'Recto femoral',
  'Vastus lateralis muscle': 'Vasto lateral',
  'Vastus medialis muscle': 'Vasto medial',
  'Vastus intermedius muscle': 'Vasto intermedio',
  'Articularis genus': 'Articular de la rodilla',
  'Pectineus muscle': 'Pectíneo',
  'Adductor longus': 'Aductor largo',
  'Adductor brevis': 'Aductor corto',
  'Adductor magnus': 'Aductor mayor',
  'Adductor minimus overlay': 'Aductor mínimo',
  'Gracilis muscle': 'Grácil (recto interno)',
  'Long head of biceps femoris': 'Bíceps femoral (cabeza larga)',
  'Short head of biceps femoris': 'Bíceps femoral (cabeza corta)',
  'Common tendon of biceps femoris': 'Tendón del bíceps femoral',
  'Common tendon of Semitendinosus and Long head of biceps femoris': 'Tendón común del semitendinoso y del bíceps femoral',
  'Semitendinosus muscle': 'Semitendinoso',
  'Semimembranosus muscle': 'Semimembranoso',
  'Semimembranosus muscle tendon': 'Tendón del semimembranoso',
  'Pes anserinus common tendon': 'Tendón común de la pata de ganso',
  'Tibialis anterior muscle': 'Tibial anterior',
  'Extensor digitorum longus': 'Extensor largo de los dedos',
  'Extensor digitorum longus tendons': 'Tendones del extensor largo de los dedos',
  'Extensor hallucis longus': 'Extensor largo del dedo gordo',
  'Fibularis tertius muscle': 'Fibular tercero',
  'Fibularis longus muscle': 'Fibular largo (peroneo largo)',
  'Fibularis brevis muscle': 'Fibular corto (peroneo corto)',
  'Medial head of gastrocnemius': 'Gastrocnemio (cabeza medial)',
  'Lateral head of gastrocnemius': 'Gastrocnemio (cabeza lateral)',
  'Soleus muscle': 'Sóleo',
  'Calcaneal tendon': 'Tendón calcáneo (de Aquiles)',
  'Plantaris muscle': 'Plantar delgado',
  'Popliteus muscle': 'Poplíteo',
  'Flexor digitorum longus': 'Flexor largo de los dedos',
  'Flexor hallucis longus': 'Flexor largo del dedo gordo',
  'Tibialis posterior muscle': 'Tibial posterior',
  'Extensor digitorum brevis': 'Extensor corto de los dedos (pedio)',
  'Extensor hallucis brevis': 'Extensor corto del dedo gordo',
  'Abductor hallucis': 'Abductor del dedo gordo',
  'Flexor digitorum brevis': 'Flexor corto de los dedos',
  'Quadratus plantae muscle': 'Cuadrado plantar',
  'Lumbrical muscles of foot': 'Lumbricales del pie',
  'Medial head of flexor hallucis brevis': 'Flexor corto del dedo gordo (cabeza medial)',
  'Lateral head of flexor hallucis brevis': 'Flexor corto del dedo gordo (cabeza lateral)',
  'Oblique head of adductor hallucis': 'Aductor del dedo gordo (cabeza oblicua)',
  'Transverse head of adductor hallucis': 'Aductor del dedo gordo (cabeza transversa)',
  'Abductor digiti minimi of foot': 'Abductor del quinto dedo',
  'Flexor digiti minimi brevis of foot': 'Flexor corto del quinto dedo',
  'Opponens digiti minimi muscle of foot': 'Oponente del quinto dedo',
  'Plantar interossei muscles': 'Interóseos plantares',

  // ── Arterias ──
  'Brachiocephalic artery': 'Tronco braquiocefálico',
  'Common carotid artery': 'Arteria carótida común',
  'Vertebral artery': 'Arteria vertebral',
  'Subclavian artery': 'Arteria subclavia',
  'Thyrocervical trunk': 'Tronco tirocervical',
  'Costocervical trunk': 'Tronco costocervical',
  'Internal thoracic artery': 'Arteria torácica interna (mamaria interna)',
  'Transverse cervical artery': 'Arteria cervical transversa',
  'Superficial branch of Transverse cervical artery': 'Rama superficial de la a. cervical transversa',
  'Dorsal scapular artery (Deep br of transverse cervical a.)': 'Arteria escapular dorsal',
  'Suprascapular artery': 'Arteria supraescapular',
  'Axillary artery': 'Arteria axilar',
  'Superior thoracic artery': 'Arteria torácica superior',
  'Thoracoacromial artery Acromial br': 'Rama acromial de la a. toracoacromial',
  'Thoracoacromial artery Deltoid br': 'Rama deltoidea de la a. toracoacromial',
  'Thoracoacromial artery Pectoral br': 'Rama pectoral de la a. toracoacromial',
  'Lateral thoracic artery': 'Arteria torácica lateral',
  'Subscapular artery': 'Arteria subescapular',
  'Circumflex scapular artery': 'Arteria circunfleja de la escápula',
  'Thoracodorsal artery': 'Arteria toracodorsal',
  'Anterior circumflex humeral artery': 'Arteria circunfleja humeral anterior',
  'Posterior circumflex humeral artery': 'Arteria circunfleja humeral posterior',
  'Brachial artery': 'Arteria braquial (humeral)',
  'Deep artery of arm': 'Arteria braquial profunda',
  'Radial collateral artery': 'Arteria colateral radial',
  'Middle collateral artery': 'Arteria colateral media',
  'Superior ulnar collateral artery': 'Arteria colateral cubital superior',
  'Inferior ulnar collateral artery': 'Arteria colateral cubital inferior',
  'Radial artery': 'Arteria radial',
  'Radial recrurrent artery': 'Arteria recurrente radial',
  'Ulnar artery': 'Arteria cubital',
  'Ulnar artery (dorsal carpal br)': 'Rama carpiana dorsal de la a. cubital',
  'Anterior ulnar recurrent artery': 'Arteria recurrente cubital anterior',
  'Posterior ulnar recurrent artery': 'Arteria recurrente cubital posterior',
  'Common interosseous artery': 'Arteria interósea común',
  'Anterior interosseous artery': 'Arteria interósea anterior',
  'Posterior interosseous artery': 'Arteria interósea posterior',
  'Interosseous recurrent artery': 'Arteria interósea recurrente',
  'Palmar carpal branches': 'Ramas carpianas palmares',
  'Dorsal carpal arch': 'Arco carpiano dorsal',
  'Dorsal carpal network': 'Red carpiana dorsal',
  'Superficial palmar arch': 'Arco palmar superficial',
  'Deep palmar arch': 'Arco palmar profundo',
  'Common palmar digital arteries': 'Arterias digitales palmares comunes',
  'Proper palmar digital arteries': 'Arterias digitales palmares propias',
  'Palmar metacarpal arteries': 'Arterias metacarpianas palmares',
  'Dorsal metacarpal arteries': 'Arterias metacarpianas dorsales',
  'Dorsal digital arteries': 'Arterias digitales dorsales de la mano',
  'Perforating arteries': 'Ramas perforantes del arco palmar profundo',
  'Princeps pollicis arteries': 'Arteria principal del pulgar',
  'Radialis indicis': 'Arteria radial del índice',
  'Dorsalis pollicis': 'Arteria dorsal del pulgar',
  'Dorsalis indicis': 'Arteria dorsal del índice',
  'Femoral artery': 'Arteria femoral',
  'Superficial epigastric artery': 'Arteria epigástrica superficial',
  'Superficial circumflex iliac artery': 'Arteria circunfleja ilíaca superficial',
  'Superficial external pudendal artery': 'Arteria pudenda externa superficial',
  'Deep artery of the thigh': 'Arteria femoral profunda',
  '1th to 4th perforating branches of the deep femoral artery': 'Arterias perforantes (1.ª a 4.ª) de la femoral profunda',
  'Medial circumflex femoral artery': 'Arteria circunfleja femoral medial',
  'Lateral circumflex femoral artery': 'Arteria circunfleja femoral lateral',
  'Ascending branch of lateral circumflex femoral artery': 'Rama ascendente de la a. circunfleja femoral lateral',
  'Descending branch of lateral circumflex femoral artery': 'Rama descendente de la a. circunfleja femoral lateral',
  'Femoral neck vessels': 'Vasos del cuello del fémur',
  'Descending genicular artery': 'Arteria descendente de la rodilla',
  'Popliteal artery': 'Arteria poplítea',
  'Superior lateral genicular artery': 'Arteria superior lateral de la rodilla',
  'Superior medial genicular artery': 'Arteria superior medial de la rodilla',
  'Middle genicular artery': 'Arteria media de la rodilla',
  'Inferior lateral genicular artery': 'Arteria inferior lateral de la rodilla',
  'Inferior medial genicular artery': 'Arteria inferior medial de la rodilla',
  'Sural artery': 'Arterias surales',
  'Anterior tibial artery': 'Arteria tibial anterior',
  'Anterior tibial recurrent artery': 'Arteria recurrente tibial anterior',
  'Posterior tibial recurrent artery': 'Arteria recurrente tibial posterior',
  'Anterior lateral malleolar artery': 'Arteria maleolar anterior lateral',
  'Anterior medial malleolar artery': 'Arteria maleolar anterior medial',
  'Posterior tibial artery': 'Arteria tibial posterior',
  'Medial malleolar artery of Posterior tibial artery': 'Ramas maleolares mediales de la a. tibial posterior',
  'Medial calcaneal artery': 'Ramas calcáneas mediales',
  'Communicating br.of Posterior tibial a. and Femoral a': 'Rama comunicante de la a. tibial posterior',
  'Fibular artery': 'Arteria fibular (peronea)',
  'Perforating branches of fibular artery': 'Rama perforante de la a. fibular',
  'Lateral malleolar branches of Fibular artery': 'Ramas maleolares laterales de la a. fibular',
  'Lateral calcaneal branch of fibular artery': 'Ramas calcáneas laterales de la a. fibular',
  'Dorsal pedis artery': 'Arteria dorsal del pie (pedia)',
  'Lateral tarsal artery': 'Arteria tarsiana lateral',
  'Medial tarsal arteries': 'Arterias tarsianas mediales',
  'Arcuate artery': 'Arteria arqueada',
  'Dorsal metatarsal arteries': 'Arterias metatarsianas dorsales',
  'Dorsal digital arteries of foot': 'Arterias digitales dorsales del pie',
  'Deep plantar artery': 'Arteria plantar profunda',
  'Perforating br. between Arcuate a. and Deep plantar arch': 'Rama perforante entre la a. arqueada y el arco plantar',
  'Medial plantar artery': 'Arteria plantar medial',
  'Superficial branch of Medial planter artery': 'Rama superficial de la a. plantar medial',
  'Deep branch of Medial plantar artery': 'Rama profunda de la a. plantar medial',
  'Lateral plantar artery': 'Arteria plantar lateral',
  'Deep plantar arch': 'Arco plantar profundo',
  'Plantar metatarsal arteries': 'Arterias metatarsianas plantares',

  // ── Venas ──
  'External jugular vein': 'Vena yugular externa',
  'Subclavian vein': 'Vena subclavia',
  'Axillary vein': 'Vena axilar',
  'Lateral thoracic vein': 'Vena torácica lateral',
  'Arm superficial vein-Cephalic vein': 'Vena cefálica',
  'Arm superficial vein-Basilic vein': 'Vena basílica',
  'Arm superficial vein-Median cubital vein': 'Vena mediana del codo',
  'Arm superficial vein-Median antebrachial vein': 'Vena mediana del antebrazo',
  'Superficial veins of upper limb': 'Venas superficiales del miembro superior',
  'Deep veins of the arm': 'Venas braquiales',
  'Radial veins': 'Venas radiales',
  'Ulnar veins': 'Venas cubitales',
  'Anterior interosseous veins': 'Venas interóseas anteriores',
  'Posterior interosseous veins': 'Venas interóseas posteriores',
  'Dorsal venous network': 'Red venosa dorsal de la mano',
  'Palmar venous network': 'Red venosa palmar',
  'Superficial palmar venous arch': 'Arco venoso palmar superficial',
  'Deep venous palmar arch': 'Arco venoso palmar profundo',
  'Palmar metacarpal veins': 'Venas metacarpianas palmares',
  'Palmal digital veins': 'Venas digitales palmares',
  'Intercapitular veins': 'Venas intercapitulares de la mano',
  'Dorsal metatarsal veins': { s: 'Venas metacarpianas dorsales', i: 'Venas metatarsianas dorsales' },
  'Dorsal digital veins': { s: 'Venas digitales dorsales de la mano', i: 'Venas digitales dorsales del pie' },
  'Femoral vein': 'Vena femoral',
  'Deep femoral vein': 'Vena femoral profunda',
  '1th to 4th perforating branches of the deep femoral vein': 'Venas perforantes (1.ª a 4.ª) de la femoral profunda',
  'Medial circumflex femoral vein': 'Vena circunfleja femoral medial',
  'Lateral circumflex femoral vein': 'Vena circunfleja femoral lateral',
  'Superficial epigastric vein': 'Vena epigástrica superficial',
  'Superficial circumflex iliac vein': 'Vena circunfleja ilíaca superficial',
  'Superficial external pudendal vein': 'Vena pudenda externa superficial',
  'Anterior femoral cutaneous vein': 'Vena cutánea femoral anterior',
  'Great saphenous vein': 'Vena safena mayor',
  'Accessory saphenous vein': 'Vena safena accesoria',
  'Small saphenous vein': 'Vena safena menor',
  'Tributary veins of Great and small saphenous veins': 'Afluentes de las safenas mayor y menor',
  'Posterior arch veins': 'Vena del arco posterior (de Leonardo)',
  "Perforating branches (Boyd's veins)": 'Venas perforantes de Boyd',
  "Perforating branches (Cockett's veins)": 'Venas perforantes de Cockett',
  "Perforating branches (Dodd's veins)": 'Venas perforantes de Dodd',
  'Popliteal vein': 'Vena poplítea',
  'Superior lateral genicular vein': 'Vena superior lateral de la rodilla',
  'Superior medial genicular vein': 'Vena superior medial de la rodilla',
  'Middle genicular vein': 'Vena media de la rodilla',
  'Inferior lateral genicular vein': 'Vena inferior lateral de la rodilla',
  'Inferior medial genicular vein': 'Vena inferior medial de la rodilla',
  'Sural vein': 'Venas surales',
  'Anterior tibial vein': 'Venas tibiales anteriores',
  'Posterior tibial vein': 'Venas tibiales posteriores',
  'Fibular vein': 'Venas fibulares',
  'Dorsal venous arch of foot': 'Arco venoso dorsal del pie',
  'Dorsal venous network of foot': 'Red venosa dorsal del pie',
  'Medial marginal vein': 'Vena marginal medial del pie',
  'Lateral marginal vein': 'Vena marginal lateral del pie',
  'Dorsal digital vein of medial side of great toe': 'Vena digital dorsal medial del dedo gordo',
  'Accompanying veins of arcuate and dorsal arteries': 'Venas satélites de las arterias arqueada y dorsal del pie',
  'Accompanying veins of dorsal digital metatarsal arteries': 'Venas satélites de las arterias metatarsianas dorsales',
  'Intercapitular veins of foot': 'Venas intercapitulares del pie',
  'Plantar venous arch': 'Arco venoso plantar',
  'Medial plantar vein': 'Venas plantares mediales',
  'Lateral plantar vein': 'Venas plantares laterales',
  'Plantar metatarsal veins': 'Venas metatarsianas plantares',
  'Plantar digital veins': 'Venas digitales plantares',

  // ── Nervios del miembro superior ──
  'Superior trunk of brachial plexus': 'Tronco superior del plexo braquial',
  'Middle trunk of brachial plexus': 'Tronco medio del plexo braquial',
  'Inferior trunk of brachial plexus': 'Tronco inferior del plexo braquial',
  'Anterior divisions of brachial plexus': 'Divisiones anteriores del plexo braquial',
  'Posterior divisions of brachial plexus': 'Divisiones posteriores del plexo braquial',
  'Lateral cord of brachial plexus': 'Fascículo lateral del plexo braquial',
  'Medial cord of brachial plexus': 'Fascículo medial del plexo braquial',
  'Posterior cord of brachial plexus': 'Fascículo posterior del plexo braquial',
  'Dorsal scapular nerve': 'Nervio escapular dorsal',
  'Long thoracic nerve': 'Nervio torácico largo (de Bell)',
  'Subclavian nerve': 'Nervio del subclavio',
  'Suprascapular nerve': 'Nervio supraescapular',
  'Lateral pectoral nerve': 'Nervio pectoral lateral',
  'Medial pectoral nerve': 'Nervio pectoral medial',
  'Upper subscapular nerve': 'Nervio subescapular superior',
  'Lower subscapular nerve': 'Nervio subescapular inferior',
  'Axillary nerve - superior lateral br cutaneous nerve': 'Nervio axilar (y n. cutáneo lateral superior del brazo)',
  'Musculocutaneus nerve': 'Nervio musculocutáneo',
  'Musculocutaneus nerve - lateral antebrachial cutaneous nerve': 'Nervio cutáneo lateral del antebrazo (musculocutáneo)',
  'Medial brachial cutaneous nerve': 'Nervio cutáneo medial del brazo',
  'Medial antebrachial cutaneous nerve': 'Nervio cutáneo medial del antebrazo',
  'Lateral root of median nerve': 'Raíz lateral del nervio mediano',
  'Medial root of median nerve': 'Raíz medial del nervio mediano',
  'Median nerve': 'Nervio mediano',
  'Median nerve Palmar br': 'Rama palmar del n. mediano',
  'Median nerve Recurrent br': 'Rama recurrente (tenar) del n. mediano',
  'Median nerve Common palmar digital nerves': 'Nervios digitales palmares comunes (mediano)',
  'Median nerve Common palmar digital nerve of the thumb': 'Nervio digital palmar común del pulgar (mediano)',
  'Median nerve Proper palmar digital nerves': 'Nervios digitales palmares propios (mediano)',
  'Median nerve Proper palmar digital nerves of the thumb': 'Nervios digitales palmares propios del pulgar (mediano)',
  'Ulnar nerve': 'Nervio cubital',
  'Ulnar nerve Dorsal cutaneous br': 'Rama cutánea dorsal del n. cubital',
  'Ulnar nerve Palmar cutaneous br': 'Rama cutánea palmar del n. cubital',
  'Ulnar nerve Deep br': 'Rama profunda del n. cubital',
  'Ulnar nerve Communicating br': 'Rama comunicante del n. cubital con el mediano',
  'Ulnar nerve Superficial br Common palmar digital n': 'Nervio digital palmar común (cubital)',
  'Ulnar nerve Superficial br Proper palmar digital nn': 'Nervios digitales palmares propios (cubital)',
  'Radial nerve': 'Nervio radial',
  'Radial nerve (deep branch)': 'Rama profunda del n. radial',
  'Radial nerve (superficial br)': 'Rama superficial del n. radial',
  'Radial nerve (posterior interosseus n)': 'Nervio interóseo posterior (radial)',
  'Radial nerve (posterior brachial cutaneous n)': 'Nervio cutáneo posterior del brazo (radial)',
  'Radial nerve (inferior lateral brachial cutaneous n)': 'Nervio cutáneo lateral inferior del brazo (radial)',
  'Radial nerve (posterior antebrachial cutaneous n)': 'Nervio cutáneo posterior del antebrazo (radial)',
  'Radial nerve (dorsal digital nn)': 'Nervios digitales dorsales (radial)',

  // ── Nervios del miembro inferior ──
  'Spinal cord curve Spinal cord': 'Médula espinal',
  'Arachnoid mater': 'Aracnoides',
  'Sympathic trunk': 'Tronco simpático',
  'Lumbar plexus': 'Plexo lumbar',
  'Sacral plexus': 'Plexo sacro',
  'Lumbosacral Trunk': 'Tronco lumbosacro',
  'Coccygeal nerve': 'Nervio coccígeo',
  'Iliohypogastric nerve, anterior branch': 'Rama anterior del n. iliohipogástrico',
  'Iliohypogastric nerve, lateral cutaneous branch': 'Rama cutánea lateral del n. iliohipogástrico',
  'Ilioinguinal nerve': 'Nervio ilioinguinal',
  'Genitofemoral nerve, femoral branch': 'Rama femoral del n. genitofemoral',
  'Genitofemoral nerve, genital branch': 'Rama genital del n. genitofemoral',
  'Lateral femoral cuteneous nerve': 'Nervio cutáneo femoral lateral',
  'Nerve to psoas major and iliacus': 'Ramos del psoas mayor y del ilíaco',
  'Femoral nerve': 'Nervio femoral (crural)',
  'Femoral nerve, muscular branches': 'Ramos musculares del n. femoral',
  'Femoral nerve, anterior cutaneous branches': 'Ramos cutáneos anteriores del n. femoral',
  'Saphenous branch of Femoralis nerve': 'Nervio safeno',
  'Infrapatellar branch of Saphenous nerve': 'Rama infrarrotuliana del n. safeno',
  'Saphenous nerve (Medial crural cutaneous branches)': 'Ramos cutáneos crurales mediales (n. safeno)',
  'Obturator nerve': 'Nervio obturador',
  'Obturator nerve, anterior branch': 'Rama anterior del n. obturador',
  'Obturator nerve, posterior branch': 'Rama posterior del n. obturador',
  'Obturator nerve, anterior br, cutaneous br': 'Rama cutánea del n. obturador',
  'Superior gluteal nerve': 'Nervio glúteo superior',
  'Inferior gluteal nerve': 'Nervio glúteo inferior',
  'Nerve to obturator internus (and superior gemellus)': 'Nervio del obturador interno (y gemelo superior)',
  'Nerve to quadratus femoris': 'Nervio del cuadrado femoral (y gemelo inferior)',
  'Nerve to Levator ani and coccygeus': 'Nervio del elevador del ano y del coccígeo',
  'Pudendal nerve': 'Nervio pudendo',
  'Posterior cutaneous nerve of the thigh': 'Nervio cutáneo femoral posterior',
  'Inferior clunial br. of Post. cutaneous nerve of the thigh': 'Nervios clúneos inferiores',
  'Superior clunial nerve (posterior rami)': 'Nervios clúneos superiores',
  'Sciatic nerve': 'Nervio ciático',
  'Tibial nerve': 'Nervio tibial (ciático poplíteo interno)',
  'Medial calcaneal branches of Tibial nerve': 'Ramos calcáneos mediales del n. tibial',
  'Medial plantar nerve': 'Nervio plantar medial',
  'Lateral plantar nerve': 'Nervio plantar lateral',
  'Superficial branch of Lateral plantar nerve': 'Rama superficial del n. plantar lateral',
  'Deep branch of Lateral plantar nerve': 'Rama profunda del n. plantar lateral',
  'Common plantar digital nerves': 'Nervios digitales plantares comunes',
  'Proper plantar digital branches (Medial plantar nerve)': 'Nervios digitales plantares propios (n. plantar medial)',
  'Proper plantar digital branches (Lateral plantar nerve)': 'Nervios digitales plantares propios (n. plantar lateral)',
  'Common fibular nerve': 'Nervio fibular común (ciático poplíteo externo)',
  'Superficial fibular nerve': 'Nervio fibular superficial (musculocutáneo de la pierna)',
  'Medial dorsal cutaneous nerve': 'Nervio cutáneo dorsal medial del pie',
  'Dorsal digital branches of superficial fibular nerve': 'Nervios digitales dorsales del n. fibular superficial',
  'Deep fibular nerve': 'Nervio fibular profundo (tibial anterior)',
  'Medial branch of deep fibular nerve': 'Rama medial del n. fibular profundo',
  'Lateral branch of deep fibular nerve': 'Rama lateral del n. fibular profundo',
  'Dorsal digital branches of deep fibular nerve': 'Nervios digitales dorsales del n. fibular profundo',
  'Lateral sural cutaneous nerve': 'Nervio cutáneo sural lateral',
  'Medial sural cutaneous nerve': 'Nervio cutáneo sural medial',
  'Sural nerve': 'Nervio sural',
  'Sural nerve, Lateral dorsal cutaneous nerve': 'Nervio cutáneo dorsal lateral del pie (sural)',
  'Lateral dorsal cutaneous nerve': 'Nervio cutáneo dorsal lateral del pie',
  'Lateral calcaneal nerves': 'Ramos calcáneos laterales (n. sural)',
};
