// Nombre en español de cada pieza de BodyParts3D, por su nombre en inglés.
//
// Sin lado: el lado va aparte en el manifiesto (`lado`), así la misma
// traducción sirve para el espejo izquierdo y el visor lo añade solo cuando hay
// piezas de los dos lados a la vista. Nomenclatura: Terminología Anatómica en
// español. Una pieza sin entrada aquí hace fallar la extracción.

export const NOMBRES = {
  // ─── Huesos ────────────────────────────────────────────────────────────────
  'Right clavicle': 'Clavícula',
  'Right scapula': 'Escápula',
  'Right first rib': 'Primera costilla',
  'Right second rib': 'Segunda costilla',
  'Right third rib': 'Tercera costilla',
  'Right fourth rib': 'Cuarta costilla',
  'Right fifth rib': 'Quinta costilla',
  'Right sixth rib': 'Sexta costilla',
  'Right first costal cartilage': 'Primer cartílago costal',
  'Right second costal cartilage': 'Segundo cartílago costal',
  'Right third costal cartilage': 'Tercer cartílago costal',
  'Right fourth costal cartilage': 'Cuarto cartílago costal',
  'Right fifth costal cartilage': 'Quinto cartílago costal',
  'Right sixth costal cartilage': 'Sexto cartílago costal',
  'Right seventh rib': 'Séptima costilla',
  'Right eighth rib': 'Octava costilla',
  'Right ninth rib': 'Novena costilla',
  'Right seventh costal cartilage': 'Séptimo cartílago costal',
  'Manubrium': 'Manubrio del esternón',
  'Body of sternum': 'Cuerpo del esternón',
  'Xiphoid process': 'Apófisis xifoides',
  'Occipital bone': 'Occipital',
  'Mandible': 'Mandíbula',
  'Atlas': 'Atlas (C1)',
  'Axis': 'Axis (C2)',
  'Third cervical vertebra': 'Vértebra C3',
  'Fourth cervical vertebra': 'Vértebra C4',
  'Fifth cervical vertebra': 'Vértebra C5',
  'Sixth cervical vertebra': 'Vértebra C6',
  'Seventh cervical vertebra': 'Vértebra C7',
  'First thoracic vertebra': 'Vértebra T1',
  'Second thoracic vertebra': 'Vértebra T2',
  'Third thoracic vertebra': 'Vértebra T3',
  'Fourth thoracic vertebra': 'Vértebra T4',
  'Fifth thoracic vertebra': 'Vértebra T5',
  'Sixth thoracic vertebra': 'Vértebra T6',
  'Seventh thoracic vertebra': 'Vértebra T7',
  'Eighth thoracic vertebra': 'Vértebra T8',
  'Ninth thoracic vertebra': 'Vértebra T9',
  'Tenth thoracic vertebra': 'Vértebra T10',
  'Eleventh thoracic vertebra': 'Vértebra T11',
  // El disco «de la vértebra N» es el que queda debajo de ella (entre atlas y
  // axis no hay disco).
  'Intervertebral disk of axis': 'Disco intervertebral C2-C3',
  'Intervertebral disk of third cervical vertebra': 'Disco intervertebral C3-C4',
  'Intervertebral disk of fourth cervical vertebra': 'Disco intervertebral C4-C5',
  'Intervertebral disk of fifth cervical vertebra': 'Disco intervertebral C5-C6',
  'Intervertebral disk of sixth cervical vertebra': 'Disco intervertebral C6-C7',
  'Intervertebral disk of seventh cervical vertebra': 'Disco intervertebral C7-T1',
  'Intervertebral disk of first thoracic vertebra': 'Disco intervertebral T1-T2',
  'Intervertebral disk of second thoracic vertebra': 'Disco intervertebral T2-T3',
  'Intervertebral disk of third thoracic vertebra': 'Disco intervertebral T3-T4',
  'Intervertebral disk of fourth thoracic vertebra': 'Disco intervertebral T4-T5',
  'Intervertebral disk of fifth thoracic vertebra': 'Disco intervertebral T5-T6',
  'Intervertebral disk of sixth thoracic vertebra': 'Disco intervertebral T6-T7',
  'Intervertebral disk of seventh thoracic vertebra': 'Disco intervertebral T7-T8',
  'Intervertebral disk of eighth thoracic vertebra': 'Disco intervertebral T8-T9',
  'Intervertebral disk of ninth thoracic vertebra': 'Disco intervertebral T9-T10',
  'Intervertebral disk of tenth thoracic vertebra': 'Disco intervertebral T10-T11',
  'Intervertebral disk of eleventh thoracic vertebra': 'Disco intervertebral T11-T12',
  'Right humerus': 'Húmero',
  'Right radius': 'Radio',
  'Right ulna': 'Cúbito',
  'Right scaphoid': 'Escafoides',
  'Right lunate': 'Semilunar',
  'Right triquetral': 'Piramidal',
  'Right pisiform': 'Pisiforme',
  'Right trapezium': 'Trapecio (hueso)',
  'Right trapezoid': 'Trapezoide',
  'Right capitate': 'Grande',
  'Right hamate': 'Ganchoso',
  'Right first metacarpal bone': 'Primer metacarpiano',
  'Right second metacarpal bone': 'Segundo metacarpiano',
  'Right third metacarpal bone': 'Tercer metacarpiano',
  'Right fourth metacarpal bone': 'Cuarto metacarpiano',
  'Right fifth metacarpal bone': 'Quinto metacarpiano',
  'Proximal phalanx of right thumb': 'Falange proximal del pulgar',
  'Distal phalanx of right thumb': 'Falange distal del pulgar',
  'Proximal phalanx of right index finger': 'Falange proximal del índice',
  'Middle phalanx of right index finger': 'Falange media del índice',
  'Distal phalanx of right index finger': 'Falange distal del índice',
  'Proximal phalanx of right middle finger': 'Falange proximal del dedo medio',
  'Middle phalanx of right middle finger': 'Falange media del dedo medio',
  'Distal phalanx of right middle finger': 'Falange distal del dedo medio',
  'Proximal phalanx of right ring finger': 'Falange proximal del anular',
  'Middle phalanx of right ring finger': 'Falange media del anular',
  'Distal phalanx of right ring finger': 'Falange distal del anular',
  'Proximal phalanx of right little finger': 'Falange proximal del meñique',
  'Middle phalanx of right little finger': 'Falange media del meñique',
  'Distal phalanx of right little finger': 'Falange distal del meñique',

  // ─── Músculos: cintura escapular ───────────────────────────────────────────
  'Clavicular part of right pectoralis major': 'Pectoral mayor (porción clavicular)',
  'Sternocostal part of right pectoralis major': 'Pectoral mayor (porción esternocostal)',
  'Abdominal part of right pectoralis major': 'Pectoral mayor (porción abdominal)',
  'Right pectoralis minor': 'Pectoral menor',
  'Right subclavius': 'Subclavio',
  'Right platysma': 'Platisma',
  'Right serratus anterior': 'Serrato anterior',
  'Descending part of right trapezius': 'Trapecio (porción descendente)',
  'Transverse part of right trapezius': 'Trapecio (porción transversa)',
  'Ascending part of right trapezius': 'Trapecio (porción ascendente)',
  'Right levator scapulae': 'Elevador de la escápula',
  'Right rhomboid major': 'Romboides mayor',
  'Right rhomboid minor': 'Romboides menor',
  'Clavicular part of right deltoid': 'Deltoides (porción clavicular)',
  'Acromial part of right deltoid': 'Deltoides (porción acromial)',
  'Spinal part of right deltoid': 'Deltoides (porción espinal)',
  'Right supraspinatus': 'Supraespinoso',
  'Right infraspinatus muscle': 'Infraespinoso',
  'Right teres minor': 'Redondo menor',
  'Right teres major': 'Redondo mayor',
  'Right subscapularis': 'Subescapular',

  // ─── Músculos: brazo ───────────────────────────────────────────────────────
  'Long head of right biceps brachii': 'Bíceps braquial (cabeza larga)',
  'Short head of right biceps brachii': 'Bíceps braquial (cabeza corta)',
  'Right coracobrachialis': 'Coracobraquial',
  'Right brachialis': 'Braquial',
  'Long head of right triceps brachii': 'Tríceps braquial (cabeza larga)',
  'Lateral head of right triceps brachii': 'Tríceps braquial (cabeza lateral)',
  'Medial head of right triceps brachii': 'Tríceps braquial (cabeza medial)',

  // ─── Músculos: antebrazo ───────────────────────────────────────────────────
  'Humeral head of right pronator teres': 'Pronador redondo (cabeza humeral)',
  'Ulnar head of right pronator teres': 'Pronador redondo (cabeza cubital)',
  'Right flexor carpi radialis': 'Flexor radial del carpo',
  'Right palmaris longus': 'Palmar largo',
  'Humeral head of right flexor carpi ulnaris': 'Flexor cubital del carpo (cabeza humeral)',
  'Ulnar head of right flexor carpi ulnaris': 'Flexor cubital del carpo (cabeza cubital)',
  'Right flexor digitorum superficialis': 'Flexor superficial de los dedos',
  'Right flexor digitorum profundus': 'Flexor profundo de los dedos',
  'Right flexor pollicis longus': 'Flexor largo del pulgar',
  'Right pronator quadratus': 'Pronador cuadrado',
  'Right brachioradialis': 'Braquiorradial',
  'Right extensor carpi radialis longus': 'Extensor radial largo del carpo',
  'Right extensor carpi radialis brevis': 'Extensor radial corto del carpo',
  'Right extensor digitorum': 'Extensor de los dedos',
  'Right extensor digiti minimi': 'Extensor del meñique',
  'Right extensor carpi ulnaris': 'Extensor cubital del carpo',
  'Right anconeus': 'Ancóneo',
  'Right supinator': 'Supinador',
  'Right abductor pollicis longus': 'Abductor largo del pulgar',
  'Right extensor pollicis brevis': 'Extensor corto del pulgar',
  'Right extensor pollicis longus': 'Extensor largo del pulgar',
  'Right extensor indicis': 'Extensor del índice',

  // ─── Músculos: mano ────────────────────────────────────────────────────────
  'Right abductor pollicis brevis': 'Abductor corto del pulgar',
  'Right flexor pollicis brevis': 'Flexor corto del pulgar',
  'Superficial head of right flexor pollicis brevis': 'Flexor corto del pulgar (cabeza superficial)',
  'Right opponens pollicis': 'Oponente del pulgar',
  'Oblique head of right adductor pollicis': 'Aductor del pulgar (cabeza oblicua)',
  'Transverse head of right adductor pollicis': 'Aductor del pulgar (cabeza transversa)',
  'Abductor digiti minimi of right hand': 'Abductor del meñique',
  'Flexor digiti minimi brevis of right hand': 'Flexor corto del meñique',
  'Opponens digiti minimi of right hand': 'Oponente del meñique',
  'Set of lumbricals of right hand': 'Lumbricales',
  'Set of palmar interossei of right hand': 'Interóseos palmares',
  'Set of dorsal interossei of right hand': 'Interóseos dorsales',

  // ─── Tejido conectivo ──────────────────────────────────────────────────────
  'Interosseous membrane of right forearm': 'Membrana interósea del antebrazo',
  'Flexor retinaculum of right wrist': 'Retináculo de los flexores',

  // ─── Arterias ──────────────────────────────────────────────────────────────
  'Right subclavian artery': 'Arteria subclavia',
  'Right transverse cervical artery': 'Arteria cervical transversa',
  'Right suprascapular artery': 'Arteria supraescapular',
  'Right dorsal scapular artery': 'Arteria escapular dorsal',
  'Right axillary artery': 'Arteria axilar',
  'Trunk of right thoraco-acromial artery': 'Arteria toracoacromial',
  'Acromial branch of right thoraco-acromial artery': 'Rama acromial de la a. toracoacromial',
  'Deltoid branch of right thoraco-acromial artery': 'Rama deltoidea de la a. toracoacromial',
  'Pectoral branch of right thoraco-acromial artery': 'Rama pectoral de la a. toracoacromial',
  'Right lateral thoracic artery': 'Arteria torácica lateral',
  'Right subscapular artery': 'Arteria subescapular',
  'Right circumflex scapular artery': 'Arteria circunfleja de la escápula',
  'Right thoracodorsal artery': 'Arteria toracodorsal',
  'Right anterior circumflex humeral artery': 'Arteria circunfleja humeral anterior',
  'Right posterior circumflex humeral artery': 'Arteria circunfleja humeral posterior',
  'Right brachial artery': 'Arteria braquial',
  'Right deep brachial artery': 'Arteria braquial profunda',
  'Middle collateral branch of right deep brachial artery': 'Arteria colateral media',
  'Radial collateral branch of right deep brachial artery': 'Arteria colateral radial',
  'Right superior ulnar collateral artery': 'Arteria colateral cubital superior',
  'Right inferior ulnar collateral artery': 'Arteria colateral cubital inferior',
  'Right radial artery': 'Arteria radial',
  'Right radial recurrent artery': 'Arteria recurrente radial',
  'Right ulnar artery': 'Arteria cubital',
  'Right anterior ulnar recurrent artery': 'Arteria recurrente cubital anterior',
  'Right posterior ulnar recurrent artery': 'Arteria recurrente cubital posterior',
  'Right common interosseous artery': 'Arteria interósea común',
  'Right anterior interosseous artery': 'Arteria interósea anterior',
  'Right recurrent interosseous artery': 'Arteria interósea recurrente',
  'Dorsal carpal branch of right radial artery': 'Rama carpiana dorsal de la a. radial',
  'Right dorsal carpal branch of ulnar artery': 'Rama carpiana dorsal de la a. cubital',
  'Right superficial palmar arterial arch': 'Arco palmar superficial',
  'Right deep palmar arch': 'Arco palmar profundo',
  'Right palmar metacarpal artery': 'Arteria metacarpiana palmar',
  'Set of dorsal metacarpal arteries': 'Arterias metacarpianas dorsales',
  'Set of dorsal digital arteries': 'Arterias digitales dorsales',
  'Right arteria princeps pollicis': 'Arteria principal del pulgar',
  'Right arteria radialis indicis': 'Arteria radial del índice',
  'Right first common palmar digital artery': 'Primera arteria digital palmar común',
  'Right second common palmar digital artery': 'Segunda arteria digital palmar común',
  'Right third common palmar digital artery': 'Tercera arteria digital palmar común',
  'Right fourth common palmar digital artery': 'Cuarta arteria digital palmar común',
  'Medial proper palmar digital artery of right index finger': 'A. digital palmar propia medial del índice',
  'Lateral proper palmar digital artery of right middle finger': 'A. digital palmar propia lateral del dedo medio',
  'Medial proper palmar digital artery of right middle finger': 'A. digital palmar propia medial del dedo medio',
  'Lateral proper palmar digital artery of right ring finger': 'A. digital palmar propia lateral del anular',
  'Medial proper palmar digital artery of right ring finger': 'A. digital palmar propia medial del anular',
  'Lateral proper palmar digital artery of right little finger': 'A. digital palmar propia lateral del meñique',

  // ─── Venas ─────────────────────────────────────────────────────────────────
  'Right subclavian vein': 'Vena subclavia',
  'Right suprascapular vein': 'Vena supraescapular',
  'Right axillary vein': 'Vena axilar',
  'Right lateral thoracic vein': 'Vena torácica lateral',
  'Right subscapular vein': 'Vena subescapular',
  'Right circumflex scapular vein': 'Vena circunfleja de la escápula',
  'Right thoracodorsal vein': 'Vena toracodorsal',
  'Right anterior circumflex humeral vein': 'Vena circunfleja humeral anterior',
  'Right posterior circumflex humeral vein': 'Vena circunfleja humeral posterior',
  'Right medial brachial vein': 'Vena braquial medial',
  'Right cephalic vein': 'Vena cefálica',
  'Right basilic vein': 'Vena basílica',
  'Right median cubital vein': 'Vena mediana del codo',
  'Right median antebrachial vein': 'Vena mediana del antebrazo',
  'Right radial vein': 'Vena radial',
  'Right ulnar vein': 'Vena cubital',
  'Dorsal venous network of right hand': 'Red venosa dorsal de la mano',
  'Right superficial palmar venous arch': 'Arco venoso palmar superficial',
  'Right deep palmar venous arch': 'Arco venoso palmar profundo',
  'Right palmar metacarpal vein': 'Vena metacarpiana palmar',
  'Common palmar digital vein': 'Vena digital palmar común',
  'Proper palmar digital vein of right index finger': 'Vena digital palmar propia del índice',
  'Proper palmar digital vein of right middle finger': 'Vena digital palmar propia del dedo medio',
  'Proper palmar digital vein of right ring finger': 'Vena digital palmar propia del anular',
  'Proper palmar digital vein of right little finger': 'Vena digital palmar propia del meñique',

  // ═══ Miembro inferior ══════════════════════════════════════════════════════

  // ─── Huesos ────────────────────────────────────────────────────────────────
  'Twelfth thoracic vertebra': 'Vértebra T12',
  'First lumbar vertebra': 'Vértebra L1',
  'Second lumbar vertebra': 'Vértebra L2',
  'Third lumbar vertebra': 'Vértebra L3',
  'Fourth lumbar vertebra': 'Vértebra L4',
  'Fifth lumbar vertebra': 'Vértebra L5',
  // El disco «de la vértebra N» es el que queda debajo de ella. El que BodyParts3D
  // deja sin número es el de encima de L1.
  'Intervertebral disk': 'Disco intervertebral T12-L1',
  'Intervertebral disk of first lumbar vertebra': 'Disco intervertebral L1-L2',
  'Intervertebral disk of second lumbar vertebra': 'Disco intervertebral L2-L3',
  'Intervertebral disk of third lumbar vertebra': 'Disco intervertebral L3-L4',
  'Intervertebral disk of fourth lumbar vertebra': 'Disco intervertebral L4-L5',
  'Intervertebral disk of fifth lumbar vertebra': 'Disco intervertebral L5-S1',
  'Sacrum': 'Sacro',
  'Right hip bone': 'Coxal',
  'Right femur': 'Fémur',
  'Right patella': 'Rótula',
  'Right tibia': 'Tibia',
  'Right fibula': 'Fíbula (peroné)',
  'Right talus': 'Talus (astrágalo)',
  'Right calcaneus': 'Calcáneo',
  'Navicular bone of right foot': 'Navicular',
  'Right cuboid bone': 'Cuboides',
  'Right medial cuneiform bone': 'Cuneiforme medial',
  'Right intermediate cuneiform bone': 'Cuneiforme intermedio',
  'Right lateral cuneiform bone': 'Cuneiforme lateral',
  'Right first metatarsal bone': 'Primer metatarsiano',
  'Right second metatarsal bone': 'Segundo metatarsiano',
  'Right third metatarsal bone': 'Tercer metatarsiano',
  'Right fourth metatarsal bone': 'Cuarto metatarsiano',
  'Right fifth metatarsal bone': 'Quinto metatarsiano',
  'Sesamoid bone of right foot': 'Sesamoideos del dedo gordo',
  'Proximal phalanx of right big toe': 'Falange proximal del dedo gordo',
  'Distal phalanx of right big toe': 'Falange distal del dedo gordo',
  'Proximal phalanx of right second toe': 'Falange proximal del segundo dedo',
  'Middle phalanx of right second toe': 'Falange media del segundo dedo',
  'Distal phalanx of right second toe': 'Falange distal del segundo dedo',
  'Proximal phalanx of right third toe': 'Falange proximal del tercer dedo',
  'Middle phalanx of right third toe': 'Falange media del tercer dedo',
  'Distal phalanx of right third toe': 'Falange distal del tercer dedo',
  'Proximal phalanx of right fourth toe': 'Falange proximal del cuarto dedo',
  'Middle phalanx of right fourth toe': 'Falange media del cuarto dedo',
  'Distal phalanx of right fourth toe': 'Falange distal del cuarto dedo',
  'Proximal phalanx of right little toe': 'Falange proximal del quinto dedo',
  'Middle phalanx of right little toe': 'Falange media del quinto dedo',
  'Distal phalanx of right little toe': 'Falange distal del quinto dedo',

  // ─── Músculos ──────────────────────────────────────────────────────────────
  'Right psoas major': 'Psoas mayor',
  'Right iliacus': 'Ilíaco',
  'Right gluteus maximus': 'Glúteo mayor',
  'Right gluteus medius': 'Glúteo medio',
  'Right gluteus minimus': 'Glúteo menor',
  'Right tensor fasciae latae': 'Tensor de la fascia lata',
  'Right piriformis': 'Piriforme',
  'Right gemellus superior': 'Gemelo superior',
  'Right gemellus inferior': 'Gemelo inferior',
  'Right obturator internus': 'Obturador interno',
  'Right obturator externus': 'Obturador externo',
  'Right quadratus femoris': 'Cuadrado femoral',
  'Right sartorius': 'Sartorio',
  'Right rectus femoris': 'Recto femoral',
  'Right vastus lateralis': 'Vasto lateral',
  'Right vastus medialis': 'Vasto medial',
  'Right vastus intermedius': 'Vasto intermedio',
  'Right pectineus': 'Pectíneo',
  'Right adductor longus': 'Aductor largo',
  'Right adductor brevis': 'Aductor corto',
  'Right adductor magnus': 'Aductor mayor',
  'Right adductor minimus': 'Aductor mínimo',
  'Right gracilis': 'Grácil',
  'Long head of right biceps femoris': 'Bíceps femoral (cabeza larga)',
  'Short head of right biceps femoris': 'Bíceps femoral (cabeza corta)',
  'Right semitendinosus': 'Semitendinoso',
  'Right semimembranosus': 'Semimembranoso',
  'Right popliteus': 'Poplíteo',
  'Medial head of right gastrocnemius': 'Gastrocnemio (cabeza medial)',
  'Lateral head of right gastrocnemius': 'Gastrocnemio (cabeza lateral)',
  'Right soleus': 'Sóleo',
  'Right plantaris': 'Plantar',
  'Right tibialis anterior': 'Tibial anterior',
  'Right tibialis posterior': 'Tibial posterior',
  'Right extensor digitorum longus': 'Extensor largo de los dedos',
  'Right extensor hallucis longus': 'Extensor largo del dedo gordo',
  'Right fibularis longus': 'Fibular largo',
  'Right fibularis brevis': 'Fibular corto',
  'Right fibularis tertius': 'Fibular tercero',
  'Right flexor digitorum longus': 'Flexor largo de los dedos',
  'Right flexor hallucis longus': 'Flexor largo del dedo gordo',
  'Right extensor hallucis brevis': 'Extensor corto del dedo gordo',
  'Right abductor hallucis': 'Abductor del dedo gordo',
  'Medial head of right flexor hallucis brevis': 'Flexor corto del dedo gordo (cabeza medial)',
  'Lateral head of right flexor hallucis brevis': 'Flexor corto del dedo gordo (cabeza lateral)',
  'Oblique head of right adductor hallucis': 'Aductor del dedo gordo (cabeza oblicua)',
  'Transverse head of right adductor hallucis': 'Aductor del dedo gordo (cabeza transversa)',
  'Right flexor digitorum brevis': 'Flexor corto de los dedos',
  'Right flexor accessorius': 'Cuadrado plantar',
  'Abductor digiti minimi of right foot': 'Abductor del quinto dedo',
  'Flexor digiti minimi brevis of right foot': 'Flexor corto del quinto dedo',
  'Opponens digiti minimi of right foot': 'Oponente del quinto dedo',
  'First lumbrical of right foot': 'Primer lumbrical del pie',
  'Second lumbrical of right foot': 'Segundo lumbrical del pie',
  'Third lumbrical of right foot': 'Tercer lumbrical del pie',
  'Fourth lumbrical of right foot': 'Cuarto lumbrical del pie',
  'First plantar interosseous of right foot': 'Primer interóseo plantar',
  'Second plantar interosseous of right foot': 'Segundo interóseo plantar',
  'Third plantar interosseous of right foot': 'Tercer interóseo plantar',

  // ─── Tejido conectivo ──────────────────────────────────────────────────────
  'Right iliotibial tract': 'Tracto iliotibial',
  'Interosseous membrane of right leg': 'Membrana interósea de la pierna',
  'Right calcaneal tendon': 'Tendón calcáneo (de Aquiles)',
  'Right long plantar ligament': 'Ligamento plantar largo',

  // ─── Arterias ──────────────────────────────────────────────────────────────
  'Right common iliac artery': 'Arteria ilíaca común',
  'Right external iliac artery': 'Arteria ilíaca externa',
  'Right internal iliac artery': 'Arteria ilíaca interna',
  'Right superficial epigastric artery': 'Arteria epigástrica superficial',
  'Right femoral artery': 'Arteria femoral',
  'Right deep femoral artery': 'Arteria femoral profunda',
  'Right lateral circumflex femoral artery': 'Arteria circunfleja femoral lateral',
  'Ascending branch of right lateral circumflex femoral artery': 'Rama ascendente de la a. circunfleja femoral lateral',
  'Descending branch of right lateral circumflex femoral artery': 'Rama descendente de la a. circunfleja femoral lateral',
  'Set of perforating arteries': 'Arterias perforantes',
  'Right descending genicular artery': 'Arteria descendente de la rodilla',
  'Right popliteal artery': 'Arteria poplítea',
  'Right lateral superior genicular artery': 'Arteria superior lateral de la rodilla',
  'Right medial superior genicular artery': 'Arteria superior medial de la rodilla',
  'Right middle genicular artery': 'Arteria media de la rodilla',
  'Right inferior lateral genicular artery': 'Arteria inferior lateral de la rodilla',
  'Right inferior medial genicular artery': 'Arteria inferior medial de la rodilla',
  'Right anterior tibial artery': 'Arteria tibial anterior',
  'Right anterior tibial recurrent artery': 'Arteria recurrente tibial anterior',
  'Right posterior tibial artery': 'Arteria tibial posterior',
  'Right fibular artery': 'Arteria fibular',
  'Right dorsalis pedis artery': 'Arteria dorsal del pie',
  'Right lateral tarsal artery': 'Arteria tarsiana lateral',
  'Right arcuate artery': 'Arteria arqueada',
  'Right deep plantar artery': 'Arteria plantar profunda',
  'Dorsal digital artery of foot': 'Arteria digital dorsal del pie',
  'Distal perforating artery': 'Arteria perforante distal',
  'Right medial plantar artery': 'Arteria plantar medial',
  'Right superficial medial plantar artery': 'Rama superficial de la a. plantar medial',
  'Right lateral plantar artery': 'Arteria plantar lateral',
  'Right plantar arch': 'Arco plantar profundo',
  'Plantar metatarsal artery': 'Arteria metatarsiana plantar',
  'Set of common plantar digital arteries': 'Arterias digitales plantares comunes',
  'Set of plantar digital arteries proper': 'Arterias digitales plantares propias',

  // ─── Venas ─────────────────────────────────────────────────────────────────
  'Right common iliac vein': 'Vena ilíaca común',
  'Right external iliac vein': 'Vena ilíaca externa',
  'Right internal iliac vein': 'Vena ilíaca interna',
  'Right iliolumbar vein': 'Vena iliolumbar',
  'Right superior gluteal vein': 'Vena glútea superior',
  'Right inferior gluteal vein': 'Vena glútea inferior',
  'Right obturator vein': 'Vena obturatriz',
  'Right superficial epigastric vein': 'Vena epigástrica superficial',
  'Right femoral vein': 'Vena femoral',
  'Right deep femoral vein': 'Vena femoral profunda',
  'Right lateral circumflex femoral vein': 'Vena circunfleja femoral lateral',
  'Right medial circumflex femoral vein': 'Vena circunfleja femoral medial',
  'Set of perforating veins': 'Venas perforantes',
  'Right great saphenous vein': 'Vena safena mayor',
  'Right small saphenous vein': 'Vena safena menor',
  'Right popliteal vein': 'Vena poplítea',
  'Right genicular vein': 'Venas de la rodilla',
  'Right anterior tibial vein': 'Vena tibial anterior',
  'Right posterior tibial vein': 'Vena tibial posterior',
  'Right fibular vein': 'Vena fibular',
  'Dorsal venous arch of right foot': 'Arco venoso dorsal del pie',
  'Plantar venous arch of right foot': 'Arco venoso plantar',
  'Tributary of plantar venous arch': 'Afluente del arco venoso plantar',
  'Dorsal metatarsal vein': 'Vena metatarsiana dorsal',
  'Plantar metatarsal vein': 'Vena metatarsiana plantar',
  'Set of dorsal digital veins': 'Venas digitales dorsales del pie',
  'Set of plantar digital veins': 'Venas digitales plantares',
};
