// Nombre en español de cada pieza de BodyParts3D, por su nombre en inglés.
//
// Sin lado: el lado va aparte en el manifiesto (`lado`), así la misma
// traducción sirve para el espejo izquierdo y el visor lo añade solo cuando hay
// piezas de los dos lados a la vista. Nomenclatura: Terminología Anatómica en
// español. Una pieza sin entrada aquí hace fallar la extracción.

export const NOMBRES = {
  // ─── Huesos ────────────────────────────────────────────────────────────────
  'Right clavicle': 'Clavícula',
  'Right scapula': 'Escápula',
  'Right first rib': 'Primera costilla',
  'Right second rib': 'Segunda costilla',
  'Right third rib': 'Tercera costilla',
  'Right fourth rib': 'Cuarta costilla',
  'Right fifth rib': 'Quinta costilla',
  'Right sixth rib': 'Sexta costilla',
  'Right first costal cartilage': 'Primer cartílago costal',
  'Right second costal cartilage': 'Segundo cartílago costal',
  'Right third costal cartilage': 'Tercer cartílago costal',
  'Right fourth costal cartilage': 'Cuarto cartílago costal',
  'Right fifth costal cartilage': 'Quinto cartílago costal',
  'Right sixth costal cartilage': 'Sexto cartílago costal',
  'Right humerus': 'Húmero',
  'Right radius': 'Radio',
  'Right ulna': 'Cúbito',
  'Right scaphoid': 'Escafoides',
  'Right lunate': 'Semilunar',
  'Right triquetral': 'Piramidal',
  'Right pisiform': 'Pisiforme',
  'Right trapezium': 'Trapecio (hueso)',
  'Right trapezoid': 'Trapezoide',
  'Right capitate': 'Grande',
  'Right hamate': 'Ganchoso',
  'Right first metacarpal bone': 'Primer metacarpiano',
  'Right second metacarpal bone': 'Segundo metacarpiano',
  'Right third metacarpal bone': 'Tercer metacarpiano',
  'Right fourth metacarpal bone': 'Cuarto metacarpiano',
  'Right fifth metacarpal bone': 'Quinto metacarpiano',
  'Proximal phalanx of right thumb': 'Falange proximal del pulgar',
  'Distal phalanx of right thumb': 'Falange distal del pulgar',
  'Proximal phalanx of right index finger': 'Falange proximal del índice',
  'Middle phalanx of right index finger': 'Falange media del índice',
  'Distal phalanx of right index finger': 'Falange distal del índice',
  'Proximal phalanx of right middle finger': 'Falange proximal del dedo medio',
  'Middle phalanx of right middle finger': 'Falange media del dedo medio',
  'Distal phalanx of right middle finger': 'Falange distal del dedo medio',
  'Proximal phalanx of right ring finger': 'Falange proximal del anular',
  'Middle phalanx of right ring finger': 'Falange media del anular',
  'Distal phalanx of right ring finger': 'Falange distal del anular',
  'Proximal phalanx of right little finger': 'Falange proximal del meñique',
  'Middle phalanx of right little finger': 'Falange media del meñique',
  'Distal phalanx of right little finger': 'Falange distal del meñique',

  // ─── Músculos: cintura escapular ───────────────────────────────────────────
  'Clavicular part of right pectoralis major': 'Pectoral mayor (porción clavicular)',
  'Sternocostal part of right pectoralis major': 'Pectoral mayor (porción esternocostal)',
  'Abdominal part of right pectoralis major': 'Pectoral mayor (porción abdominal)',
  'Right pectoralis minor': 'Pectoral menor',
  'Right subclavius': 'Subclavio',
  'Right serratus anterior': 'Serrato anterior',
  'Descending part of right trapezius': 'Trapecio (porción descendente)',
  'Transverse part of right trapezius': 'Trapecio (porción transversa)',
  'Ascending part of right trapezius': 'Trapecio (porción ascendente)',
  'Right levator scapulae': 'Elevador de la escápula',
  'Right rhomboid major': 'Romboides mayor',
  'Right rhomboid minor': 'Romboides menor',
  'Clavicular part of right deltoid': 'Deltoides (porción clavicular)',
  'Acromial part of right deltoid': 'Deltoides (porción acromial)',
  'Spinal part of right deltoid': 'Deltoides (porción espinal)',
  'Right supraspinatus': 'Supraespinoso',
  'Right infraspinatus muscle': 'Infraespinoso',
  'Right teres minor': 'Redondo menor',
  'Right teres major': 'Redondo mayor',
  'Right subscapularis': 'Subescapular',

  // ─── Músculos: brazo ───────────────────────────────────────────────────────
  'Long head of right biceps brachii': 'Bíceps braquial (cabeza larga)',
  'Short head of right biceps brachii': 'Bíceps braquial (cabeza corta)',
  'Right coracobrachialis': 'Coracobraquial',
  'Right brachialis': 'Braquial',
  'Long head of right triceps brachii': 'Tríceps braquial (cabeza larga)',
  'Lateral head of right triceps brachii': 'Tríceps braquial (cabeza lateral)',
  'Medial head of right triceps brachii': 'Tríceps braquial (cabeza medial)',

  // ─── Músculos: antebrazo ───────────────────────────────────────────────────
  'Humeral head of right pronator teres': 'Pronador redondo (cabeza humeral)',
  'Ulnar head of right pronator teres': 'Pronador redondo (cabeza cubital)',
  'Right flexor carpi radialis': 'Flexor radial del carpo',
  'Right palmaris longus': 'Palmar largo',
  'Humeral head of right flexor carpi ulnaris': 'Flexor cubital del carpo (cabeza humeral)',
  'Ulnar head of right flexor carpi ulnaris': 'Flexor cubital del carpo (cabeza cubital)',
  'Right flexor digitorum superficialis': 'Flexor superficial de los dedos',
  'Right flexor digitorum profundus': 'Flexor profundo de los dedos',
  'Right flexor pollicis longus': 'Flexor largo del pulgar',
  'Right pronator quadratus': 'Pronador cuadrado',
  'Right brachioradialis': 'Braquiorradial',
  'Right extensor carpi radialis longus': 'Extensor radial largo del carpo',
  'Right extensor carpi radialis brevis': 'Extensor radial corto del carpo',
  'Right extensor digitorum': 'Extensor de los dedos',
  'Right extensor digiti minimi': 'Extensor del meñique',
  'Right extensor carpi ulnaris': 'Extensor cubital del carpo',
  'Right anconeus': 'Ancóneo',
  'Right supinator': 'Supinador',
  'Right abductor pollicis longus': 'Abductor largo del pulgar',
  'Right extensor pollicis brevis': 'Extensor corto del pulgar',
  'Right extensor pollicis longus': 'Extensor largo del pulgar',
  'Right extensor indicis': 'Extensor del índice',

  // ─── Músculos: mano ────────────────────────────────────────────────────────
  'Right abductor pollicis brevis': 'Abductor corto del pulgar',
  'Right flexor pollicis brevis': 'Flexor corto del pulgar',
  'Superficial head of right flexor pollicis brevis': 'Flexor corto del pulgar (cabeza superficial)',
  'Right opponens pollicis': 'Oponente del pulgar',
  'Oblique head of right adductor pollicis': 'Aductor del pulgar (cabeza oblicua)',
  'Transverse head of right adductor pollicis': 'Aductor del pulgar (cabeza transversa)',
  'Abductor digiti minimi of right hand': 'Abductor del meñique',
  'Flexor digiti minimi brevis of right hand': 'Flexor corto del meñique',
  'Opponens digiti minimi of right hand': 'Oponente del meñique',
  'Set of lumbricals of right hand': 'Lumbricales',
  'Set of palmar interossei of right hand': 'Interóseos palmares',
  'Set of dorsal interossei of right hand': 'Interóseos dorsales',

  // ─── Tejido conectivo ──────────────────────────────────────────────────────
  'Interosseous membrane of right forearm': 'Membrana interósea del antebrazo',
  'Flexor retinaculum of right wrist': 'Retináculo de los flexores',

  // ─── Arterias ──────────────────────────────────────────────────────────────
  'Right subclavian artery': 'Arteria subclavia',
  'Right transverse cervical artery': 'Arteria cervical transversa',
  'Right suprascapular artery': 'Arteria supraescapular',
  'Right dorsal scapular artery': 'Arteria escapular dorsal',
  'Right axillary artery': 'Arteria axilar',
  'Trunk of right thoraco-acromial artery': 'Arteria toracoacromial',
  'Acromial branch of right thoraco-acromial artery': 'Rama acromial de la a. toracoacromial',
  'Deltoid branch of right thoraco-acromial artery': 'Rama deltoidea de la a. toracoacromial',
  'Pectoral branch of right thoraco-acromial artery': 'Rama pectoral de la a. toracoacromial',
  'Right lateral thoracic artery': 'Arteria torácica lateral',
  'Right subscapular artery': 'Arteria subescapular',
  'Right circumflex scapular artery': 'Arteria circunfleja de la escápula',
  'Right thoracodorsal artery': 'Arteria toracodorsal',
  'Right anterior circumflex humeral artery': 'Arteria circunfleja humeral anterior',
  'Right posterior circumflex humeral artery': 'Arteria circunfleja humeral posterior',
  'Right brachial artery': 'Arteria braquial',
  'Right deep brachial artery': 'Arteria braquial profunda',
  'Middle collateral branch of right deep brachial artery': 'Arteria colateral media',
  'Radial collateral branch of right deep brachial artery': 'Arteria colateral radial',
  'Right superior ulnar collateral artery': 'Arteria colateral cubital superior',
  'Right inferior ulnar collateral artery': 'Arteria colateral cubital inferior',
  'Right radial artery': 'Arteria radial',
  'Right radial recurrent artery': 'Arteria recurrente radial',
  'Right ulnar artery': 'Arteria cubital',
  'Right anterior ulnar recurrent artery': 'Arteria recurrente cubital anterior',
  'Right posterior ulnar recurrent artery': 'Arteria recurrente cubital posterior',
  'Right common interosseous artery': 'Arteria interósea común',
  'Right anterior interosseous artery': 'Arteria interósea anterior',
  'Right recurrent interosseous artery': 'Arteria interósea recurrente',
  'Dorsal carpal branch of right radial artery': 'Rama carpiana dorsal de la a. radial',
  'Right dorsal carpal branch of ulnar artery': 'Rama carpiana dorsal de la a. cubital',
  'Right superficial palmar arterial arch': 'Arco palmar superficial',
  'Right deep palmar arch': 'Arco palmar profundo',
  'Right palmar metacarpal artery': 'Arteria metacarpiana palmar',
  'Set of dorsal metacarpal arteries': 'Arterias metacarpianas dorsales',
  'Set of dorsal digital arteries': 'Arterias digitales dorsales',
  'Right arteria princeps pollicis': 'Arteria principal del pulgar',
  'Right arteria radialis indicis': 'Arteria radial del índice',
  'Right first common palmar digital artery': 'Primera arteria digital palmar común',
  'Right second common palmar digital artery': 'Segunda arteria digital palmar común',
  'Right third common palmar digital artery': 'Tercera arteria digital palmar común',
  'Right fourth common palmar digital artery': 'Cuarta arteria digital palmar común',
  'Medial proper palmar digital artery of right index finger': 'A. digital palmar propia medial del índice',
  'Lateral proper palmar digital artery of right middle finger': 'A. digital palmar propia lateral del dedo medio',
  'Medial proper palmar digital artery of right middle finger': 'A. digital palmar propia medial del dedo medio',
  'Lateral proper palmar digital artery of right ring finger': 'A. digital palmar propia lateral del anular',
  'Medial proper palmar digital artery of right ring finger': 'A. digital palmar propia medial del anular',
  'Lateral proper palmar digital artery of right little finger': 'A. digital palmar propia lateral del meñique',

  // ─── Venas ─────────────────────────────────────────────────────────────────
  'Right subclavian vein': 'Vena subclavia',
  'Right suprascapular vein': 'Vena supraescapular',
  'Right axillary vein': 'Vena axilar',
  'Right lateral thoracic vein': 'Vena torácica lateral',
  'Right subscapular vein': 'Vena subescapular',
  'Right circumflex scapular vein': 'Vena circunfleja de la escápula',
  'Right thoracodorsal vein': 'Vena toracodorsal',
  'Right anterior circumflex humeral vein': 'Vena circunfleja humeral anterior',
  'Right posterior circumflex humeral vein': 'Vena circunfleja humeral posterior',
  'Right medial brachial vein': 'Vena braquial medial',
  'Right cephalic vein': 'Vena cefálica',
  'Right basilic vein': 'Vena basílica',
  'Right median cubital vein': 'Vena mediana del codo',
  'Right median antebrachial vein': 'Vena mediana del antebrazo',
  'Right radial vein': 'Vena radial',
  'Right ulnar vein': 'Vena cubital',
  'Dorsal venous network of right hand': 'Red venosa dorsal de la mano',
  'Right superficial palmar venous arch': 'Arco venoso palmar superficial',
  'Right deep palmar venous arch': 'Arco venoso palmar profundo',
  'Right palmar metacarpal vein': 'Vena metacarpiana palmar',
  'Common palmar digital vein': 'Vena digital palmar común',
  'Proper palmar digital vein of right index finger': 'Vena digital palmar propia del índice',
  'Proper palmar digital vein of right middle finger': 'Vena digital palmar propia del dedo medio',
  'Proper palmar digital vein of right ring finger': 'Vena digital palmar propia del anular',
  'Proper palmar digital vein of right little finger': 'Vena digital palmar propia del meñique',
};
